import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Nav
    home: 'Home',
    schedule: 'Schedule',
    reminders: 'Reminders',
    profile: 'My Profile',
    admin: 'Admin',
    signOut: 'Sign out',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',

    // Login
    signIn: 'Sign in',
    username: 'Username',
    password: 'Password',
    signingIn: 'Signing in…',
    enterCode: 'Enter authenticator code',
    sixDigitCode: '6-digit code',
    verifying: 'Verifying…',
    verify: 'Verify',
    back: '← Back',
    orDivider: 'or',
    signInSso: 'Sign in with SSO',
    ssoErrorNoGroup: 'Your account is not a member of any portal access group — contact an admin.',
    ssoErrorDeactivated: 'This account has been deactivated — contact an admin.',
    ssoErrorGeneric: 'SSO sign-in failed — please try again or use your password.',

    // Notifications
    notifications: 'Notifications',
    markRead: 'Mark read',
    clearAll: 'Clear all',
    allClear: 'All clear',

    // Profile
    myProfile: 'My Profile',
    identity: 'Identity',
    displayName: 'Display name (shown in schedule)',
    nameColor: 'Name color',
    avatarUrl: 'Avatar URL (optional)',
    saveIdentity: 'Save identity',
    timezone: 'Timezone',
    timezoneDesc: 'All notifications and schedule times are adjusted to your timezone.',
    yourTimezone: 'Your timezone',
    currentLocalTime: 'Your current local time',
    saveTimezone: 'Save timezone',
    telegramNotifications: 'Telegram Notifications',
    linked: 'Linked',
    notLinked: 'Not linked',
    telegramUsername: 'Telegram username',
    shiftNotifications: 'Shift notifications',
    reminderNotifications: 'Reminder notifications',
    saveTelegramSettings: 'Save telegram settings',
    getLinkCode: 'Get link code',

    // Admin
    adminPanel: 'Admin Panel',
    users: 'Users',
    groups: 'Groups',
    shiftConfig: 'Shift Config',
    telegram: 'Telegram',
    notificationsTab: 'Notifications',
    logs: 'Logs',
    addUser: '+ Add user',
    allActions: 'All actions',
    noLogEntries: 'No log entries',
    noLogEntriesDesc: 'Actions will appear here as users interact with the portal',

    // Home
    homeEngineerFallback: 'engineer',
    homeAssignedEngineer: 'Assigned engineer',
    homeNoUpcomingShift: 'No upcoming shift',
    homeMyShifts: 'My shifts',
    homeOpenMail: 'Open mail',
    homeUnchecked: 'unchecked',
    homeBlocked: 'blocked',
    homeNext: 'Next',
    homeNothingScheduled: 'Nothing scheduled',
    homeCheckNotifications: 'Check notification panel',
    homeAllClear: 'All clear',
    homeNoShiftNextDays: 'No shift in next 5 days',
    homeOperationalMail: 'Operational mail',
    homeMailClear: 'Mail queue is clear',
    homeMailClearDesc: 'Latest synced emails do not need triage.',
    homeIncidents: 'Incidents:',
    homeIncidentsDesc: 'Grafana alert webhook integration will surface active incidents here.',
    homeTickets: 'Tickets:',
    homeTicketsDesc: 'Zammad sync will show active ticket load, SLA risk, and Telegram-linked cases.',
    homeRunbooks: 'Runbooks:',
    homeRunbooksDesc: 'Runbook recommendations will appear here once the knowledge module is connected.',
    homeTicketsTitle: 'Tickets',
    homeTicketsOpenFull: 'Open full view',
    homeTicketsEmpty: 'No active tickets',
    homeTicketsLoading: 'Loading tickets…',
    homeAttention: 'Needs attention',
    homeChecked: 'Checked',
    homeJustNow: 'just now',
    homeOpenMonitor: 'Open monitor',
    homeOpenTickets: 'Open tickets',
    homeOpenMailLink: 'Open mail',
    homeItems: 'items',
    homeMoreDown: 'more down',
    homeOf: 'of',
    homeUpTail: 'up',
    homeNoDataTail: 'no data',
    homeSolvedToday: 'solved today',
    homeOnPause: 'on pause',
    homeNextIn: 'Next in',
    homeDay: 'day',
    homeDays: 'days',
    homeOnTrack: 'on track',
    homeVsLastWk: 'vs last wk',
    homeYourShift: 'Your shift',
    homeOnShift: 'On shift',
    homeUntil: 'until',
    homeOffShiftToday: 'Off shift today',
    homeNextOn: 'Next on',
    homeYourNextShift: 'Your next shift',
    homeOnNow: 'On now',
    homeNextUp: 'Next up',
    homeOpenSchedule: 'Open schedule',
    homeQueueServices: 'Services',
    homeQueueTickets: 'Tickets',
    homeQueueMail: 'Mail queue',
    homeAll: 'All',
    homeAllClear: 'All clear',
    homeServicesClearLine: 'Every monitored target answered on its last probe.',
    homeTicketsClearLine: 'No unsolved tickets on the board.',
    homeMailClearLine: 'No unchecked mail in the latest queue.',
    homeRemindersClearLine: 'Nothing scheduled for you right now.',
    homeLastChecked: 'Last checked',
    homeDownFor: 'down',
    homeQuietFor: 'quiet',
    homeMore: 'more',
    homeOldest: 'oldest',
    homeTeamToday: 'Team on shift today',
    homeNobodyToday: 'Nobody is scheduled today.',
    homeAdd: 'Add',
    homeThisWeek: 'This week',
    homeRecapTickets: 'tickets closed',
    homeRecapMail: 'mail handled',
    homeRecapShifts: 'shifts worked',
    homeScopeMine: 'Mine',
    homeScopeTeam: 'Team',
    homeNoSubject: '(no subject)',
    homeVAllUp: 'all services up',
    homeVNoTickets: 'no open tickets',
    homeVMailClear: 'mail queue clear',
    homeVAnd: 'and',
    homeVOnShift: 'you are on shift until',
    homeVOffShift: 'you are off shift today',
    homePlSvcDown1: 'service down',
    homePlSvcDown2: 'services down',
    homePlSvcDown5: 'services down',
    homePlTicketOpen1: 'ticket open',
    homePlTicketOpen2: 'tickets open',
    homePlTicketOpen5: 'tickets open',
    homePlMailUnchecked1: 'email unchecked',
    homePlMailUnchecked2: 'emails unchecked',
    homePlMailUnchecked5: 'emails unchecked',
    homeStatusNoReply: 'no reply',
    homeStatusNoData: 'no data',
    homeAttnNone: 'none',
    aiTitle: 'Assistant',
    aiScope: 'schedule · time off · runbooks · mail review',
    aiHello: 'Meow! I\'m the portal assistant. I can:\n* **Schedule** — your shifts and who\'s on duty\n* **Time off** — check requests or file a vacation/day-off (goes to admin approval)\n* **Runbooks** — find the right guide, or draft one from a case (\"check ticket 82505 and make a runbook\") or from scratch — just describe the problem you solved\n* **Mail review** — \"did we miss anything this week?\", paused or onboarding emails\n* **Recaps** — \"what did we do this week?\": emails solved, tickets closed, mailboxes backed up\n* **Handover** — type `/handover` and I\'ll ask 3 quick questions one by one (or paste everything at once); the post is always in English\n\nAsk me in English or Russian!',
    aiPlaceholder: 'Ask about shifts, time off, runbooks…',
    aiThinking: 'Thinking…',
    // Mail page chrome
    mailInbox: 'Inbox',
    mailUnrouted: 'Unrouted',
    mailArchive: 'Archive',
    mailSentFolder: 'Sent',
    mailCategories: 'Categories',
    mailMailboxes: 'Mailboxes',
    mailStatusUnchecked: 'Unchecked',
    mailStatusSolved: 'Solved',
    mailStatusPaused: 'Paused',
    mailStatusBlocked: 'Blocked',
    mailNoMessages: 'No messages',
    mailNoMessagesDesc: 'Try another folder or check back later',
    mailSelectEmail: 'Select an email',
    mailSelectEmailDesc: 'Click on a message from the list to view its details and history',
    mailGeneral: 'General',
    mailFrom: 'From',
    mailMailboxLbl: 'Mailbox',
    mailReceived: 'Received',
    mailMessageBody: 'Message Body',
    mailActivity: 'Activity & Comments',
    mailLoadingHistory: 'Loading history…',
    mailNoComments: 'No comments yet.',
    mailWriteComment: 'Write a comment…',
    mailPostComment: 'Post Comment',
    mailSaving: 'Saving…',
    mailReplied: 'Replied',
    mailSentNothing: 'Nothing sent yet',
    mailSentNothingDesc: 'Replies sent from the portal will appear here',
    mailSentTag: 'Sent',
    mailFailedTag: 'Failed',
    mailLoading: 'Loading…',
    // Email replies (SMTP)
    erTitle: 'Email replies',
    erReplyBtn: 'Reply by email',
    erPlaceholder: 'Write your reply…',
    erHintFrom: 'Sends a real email from',
    erHintTo: 'to',
    erCancel: 'Cancel',
    erSend: 'Send reply',
    erSending: 'Sending…',
    erConfirm: 'Send this email reply to',
    // Tickets page chrome
    tpSubtitle: 'Zammad tickets, statuses and comments — synced live via webhooks',
    tpTabBoard: 'Tickets',
    tpTabEvents: 'Event log',
    tpAll: 'All',
    tpOpen: 'Open',
    tpPaused: 'Paused',
    tpClosed: 'Closed',
    tpSearch: 'Search #, title, assignee, customer…',
    tpNoTickets: 'No tickets',
    tpNoTicketsDesc: 'Tickets appear here from Zammad webhooks and periodic sync',
    tpNoEvents: 'No events yet',
    tpNoEventsDesc: 'Events appear once Zammad sends webhooks',
    tpColTicket: 'Ticket',
    tpColTitle: 'Title',
    tpColState: 'State',
    tpColAssignee: 'Assignee',
    tpColCustomer: 'Customer',
    tpColComments: 'Cmts',
    tpColUpdated: 'Updated',
    tpColEvent: 'Event',
    tpColReceived: 'Received',
    tpViewJson: 'View JSON →',
    tpShowing: 'Showing',
    tpOf: 'of',
    tpPrev: '← Prev',
    tpNext: 'Next →',
    // Alerts page
    // ── Service Status ──
    stTitle: 'Service Status',
    stSubtitle: 'Live blackbox probes, streamed from Prometheus',
    stInstance: 'Instance',
    stStatus: 'Status',
    stCode: 'Code',
    stTls: 'TLS',
    stCert: 'Cert expiry',
    stProbe: 'Probe',
    stDns: 'DNS',
    stAge: 'Updated',
    stUp: 'UP',
    stDown: 'DOWN',
    stStale: 'STALE',
    stDownTile: 'Down',
    st5xx: 'HTTP 5xx',
    stCerts7d: 'Certs < 7d',
    stStaleTile: 'Stale',
    stAvgLatency: 'Avg latency',
    stAllStale: 'No fresh data from any target — Prometheus has stopped pushing to the portal.',
    stNoData: 'No probe data yet',
    stNoDataDesc: 'Point Prometheus remote_write at /api/status/remote-write to populate this board.',
    tkEvOpened: 'Opened', tkEvAssigned: 'Assigned', tkEvComment: 'Comment',
    tkEvClosed: 'Closed', tkEvPaused: 'Paused', tkEvStatus: 'Status', tkEvSync: 'Sync',

    tkInStatus: 'in status',
    tkTicket: 'Ticket',
    tkLoading: 'Loading…',
    tkOpenBot: 'Open Bot',
    tkAssignee: 'Assignee',
    tkCustomer: 'Customer',
    tkRequestType: 'Request type',
    tkDescription: 'Description',
    tkCreated: 'Created',
    tkUpdated: 'Updated',
    tkComments: 'Comments',
    tkNoComments: 'No comments yet.',
    tkEventHistory: 'Events',
    tkNoEvents: 'No events yet.',
    tkInternalNote: 'Internal note',
    tkNotePlaceholder: 'Write a note…',
    tkNoteHint: 'Portal only — nothing is sent to the customer',
    tkAddNote: 'Add note',
    tkSending: 'Sending…',
    tkPortalOnly: 'Internal · portal only',
    tkCustomerTag: 'customer',
    tkStateNew: 'New',
    tkStateOpen: 'Open',
    tkStateInProgress: 'In progress',
    tkStateOnPause: 'On pause',
    tkStateClosed: 'Closed',

    // Schedule
    schedule_title: 'Schedule',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    today: 'Today',
    timeOff: 'Time off',
    addShift: '+ Shift',
    generate: 'Generate',
    publish: 'Publish',
    timeOffRequests: 'Time-off requests',
    noRequests: 'No requests',
    generateSchedule: 'Generate Schedule',
    start: 'Start',
    end: 'End',
    shiftTypes: 'Shift types',
    cancel: 'Cancel',
    edit: 'Edit',
    cmEdited: '(edited)',
    cmDeleteConfirm: 'Delete this comment?',
    toolMailboxBackup: 'Mailbox Backup',
    toolMbSubtitle: 'Back up a Yandex mailbox over IMAP into a compressed archive on S3 (plus per-folder .mbox files). The password is used once and never stored.',
    toolEmailLbl: 'Mailbox address',
    toolPasswordLbl: 'App password',
    toolMbHint: 'Prerequisites: IMAP access enabled on the mailbox and an app password (created in Yandex ID settings).',
    toolBatchPlaceholder: 'user@viory.video:app-password\n# more lines = more mailboxes, backed up one by one',
    toolStartBackup: 'Start backup',
    toolStarted: 'Backup started',
    toolBatchLbl: 'Mailboxes — one per line: email:password',
    toolBatchParsed: 'mailbox(es) ready',
    toolBatchBadLines: 'Unparseable lines',
    toolBatchEmpty: 'Enter at least one mailbox',
    toolJobs: 'Backup jobs',
    toolNoJobs: 'No backups yet',
    toolNotConfigured: 'Tool not configured',
    toolNotConfiguredDesc: 'S3 storage credentials are missing — ask your admin to set them in the server environment.',
    toolMessages: 'Messages',
    toolFolders: 'folders',
    toolArchive: 'Archive',
    toolDuration: 'Duration',
    toolSt_queued: 'Queued',
    toolSt_running: 'Running',
    toolSt_success: 'Success',
    toolSt_failed: 'Failed',
    toolSt_canceled: 'Canceled',
    toolCancel: 'Cancel',
    toolCancelConfirm: 'Cancel the backup of {email}? Progress will be lost.',
    toolCanceled: 'Backup canceled',
    toolPhQueued: 'Queued…',
    toolPhConnecting: 'Connecting to IMAP…',
    toolPhListing: 'Counting folders and messages…',
    toolPhFetching: 'Downloading messages',
    toolPhReconnecting: 'Connection lost — reconnecting…',
    toolEtaLbl: 'ETA',
    toolPrev: 'Previous',
    toolNext: 'Next',
    toolPageOf: 'Page {page} of {total}',
    toolPhArchiving: 'Compressing archive…',
    toolPhHashing: 'Verifying checksum…',
    toolPhUploading: 'Uploading to S3…',
    toolPhVerifying: 'Verifying upload…',
    toolPhMbox: 'Exporting .mbox files…',
    invFieldClass: 'Class',
    invClassHardware: 'Hardware',
    invClassSoftware: 'Software',
    invClassSubscription: 'Subscriptions',
    invDeviceTitle: 'Device',
    invSectionDevice: 'Device',
    invSectionProcurement: 'Purchase',
    invSectionHolder: 'Assigned to',
    invSectionComments: 'Comments',
    invFieldManufacturer: 'Manufacturer',
    invFieldLocation: 'Location',
    invFieldRack: 'Rack',
    invFieldTenant: 'Tenant',
    invFieldPrimaryIp: 'Primary IP',
    invFieldSupplier: 'Supplier',
    invFieldInvoiceNo: 'Invoice no.',
    invFieldDeliveryDate: 'Delivered',
    invFieldNetPrice: 'Net price',
    invFieldInvoice: 'Invoice',
    invFieldKitParent: 'Part of',
    invFieldSignedBy: 'Signed by',
    invFieldHandover: 'Handover',
    invNoHolder: 'Not assigned to anyone.',
    invOpenInNetbox: 'Open in NetBox',
    invOpenFile: 'Open file',
    invEdit: 'Edit',
    invTitle: 'Inventory',
    invSubtitle: 'Browse and edit devices in NetBox. Devices are never deleted from here.',
    invNotConfigured: 'Inventory not configured',
    invNotConfiguredDesc: 'NetBox URL/API token are missing — ask your admin to set them in the server environment.',
    invSearch: 'Search',
    invSearchPlaceholder: 'Name, serial, asset tag...',
    invSearchBtn: 'Search',
    invFilterAll: 'All',
    invNewDevice: 'New device',
    invEditDevice: 'Edit device',
    invNoDevices: 'No devices found',
    invSaved: 'Device saved',
    invSelectPlaceholder: 'Select…',
    invFieldName: 'Name',
    invFieldType: 'Type',
    invFieldRole: 'Role',
    invFieldSite: 'Site',
    invFieldStatus: 'Status',
    invFieldSerial: 'Serial',
    invFieldAssetTag: 'Asset tag',
    invFieldComments: 'Comments',
    handoverTitle: 'Handover Generator',
    handoverSubtitle: 'Fill in the equipment handover form and generate a signable PDF.',
    handoverEmployee: 'Employee name',
    handoverPosition: 'Position',
    handoverPeriod: 'Assignment period',
    handoverPeriodPlaceholder: 'e.g. permanent, or a date range',
    handoverPurpose: 'Purpose',
    handoverDate: 'Date',
    handoverDevices: 'Devices',
    handoverAddDevice: 'Add device',
    handoverRemoveDevice: 'Remove',
    handoverDescription: 'Description',
    handoverQty: 'Qty',
    handoverSerial: 'Serial No.',
    handoverInvNo: 'Inventory No.',
    handoverComments: 'Comments',
    handoverGenerate: 'Generate handover',
    handoverAdditionalInfo: 'Additional info',
    handoverAccessories: 'Accessories',
    handoverGenerated: 'Handover PDF generated',
    addShiftManually: 'Add Shift Manually',
    engineer: 'Engineer',
    date: 'Date',
    shiftType: 'Shift type',
    location: 'Location',
    add: 'Add',
    requestTimeOff: 'Request Time Off',
    type: 'Type',
    comment: 'Comment',
    submit: 'Submit',
    dayOff: 'Day off',
    vacation: 'Vacation',
    sickLeave: 'Sick leave',
    shift_day: 'Day',
    shift_night: 'Night',
    shift_office: 'Office',
    schedulePublished: 'published',
    scheduleDraft: 'draft',
    scheduleWeekOf: 'Week of',
    scheduleShortStaffed: 'short staffed',
    scheduleCoverageThisWeek: 'Coverage this week',
    scheduleTimeOffPanel: 'Time-off',
    scheduleRequest: 'Request',
    scheduleNoTimeOff: 'No time-off in this range',
    scheduleNoCoverage: 'No coverage data for this range',
    scheduleConflictBanner: '{{date}} {{shift}} shift has {{count}} engineer on approved leave. Consider reassigning.',
    scheduleConflictBannerMany: '{{date}} {{shift}} shift has {{count}} engineers on approved leave. Consider reassigning.',
    scheduleSuggest: 'Suggest',
    scheduleResolve: 'Resolve',
    scheduleClearDrafts: 'Clear drafts',
    scheduleGenerated: 'Schedule generated!',
    scheduleNoDrafts: 'No drafts in this range',
    scheduleDeleteDraftsConfirm: 'Delete {{count}} draft shift(s) from this view?',
    scheduleClearedDrafts: 'Cleared {{count}} draft(s)',
    scheduleShiftAdded: 'Shift added',
    scheduleTimeOffRequested: 'Time-off requested',
    scheduleDeleteShiftConfirm: 'Delete this draft shift?',
    scheduleStageForRemovalConfirm: 'This shift is published. It will be staged for removal and hidden from engineers until you click Publish.',
    scheduleStagedForRemoval: 'Staged for removal',
    scheduleUndoRemoval: 'Undo removal',
    scheduleDeleteTimeOffConfirm: 'Delete this time-off request?',
    scheduleEditShift: 'Edit Shift',
    scheduleNotes: 'Notes',
    scheduleNotesPlaceholder: 'Optional notes…',
    schedulePublishedVisible: 'Published (visible to engineers)',
    scheduleResetPending: 'Reset to pending',
    adminBlockedDates: 'Blocked Dates',
    adminBlockedDatesDesc: 'Dates this engineer cannot be assigned shifts',
    adminBlockedDatesEmpty: 'No blocked dates',
    adminBlockedDatesAdd: 'Block dates',
    adminBlockedDatesReason: 'Reason (optional)',
    save: 'Save',
    delete: 'Delete',
    reject: 'Reject',
    approve: 'Approve',
    open: 'Open',

    // Reminders
    reminders_title: 'Reminders',
    active: 'Active',
    all: 'All',
    newReminder: '+ New',
    noReminders: 'No reminders',
    noRemindersDesc: 'Create one to get started',
    cancelReminder: 'Cancel',
    newReminderTitle: 'New Reminder',
    title: 'Title',
    description: 'Description',
    quickSet: 'Quick set',
    remindAt: 'Remind at',
    recurring: 'Recurring',
    telegram: 'Telegram',
    create: 'Create',
    tomorrow: 'Tomorrow',

    // OTP
    twoFactor: 'Two-Factor Authentication',
    twoFactorDesc: 'Protect your account with an authenticator app (Google Authenticator, Authy, etc.).',
    otpActive: '2FA enabled',
    otpInactive: '2FA disabled',
    setupOtp: 'Set up 2FA',
    otpScanQr: 'Scan this QR code with your authenticator app, then enter the 6-digit code to confirm.',
    otpManualKey: 'Manual key',
    otpEnterCode: '6-digit code',
    otpConfirm: 'Confirm & enable',
    otpEnabled: '2FA enabled successfully',
    otpDisable: 'Disable 2FA',
    otpDisableDesc: 'Enter your current authenticator code to disable 2FA.',
    otpDisabled: '2FA has been disabled',

    // Time Off Page
    timeOffRequests: 'Time Off',
    timeOffDesc: 'Manage vacation, sick leave, and days off',
    noRequestsDesc: 'No requests found',
    timeOffRequested: 'Time-off requested!',

    // Telegram
    unlinkTelegram: 'Unlink',
    telegramUnlinked: 'Telegram unlinked',

    // Mail Reporter
    mailReporter: 'Mail Reporter',
    mailboxes: 'Mailboxes',
    addMailbox: '+ Add Mailbox',
    editMailbox: 'Edit Mailbox',
    deleteMailbox: 'Delete Mailbox',
    testConnection: 'Test Connection',
    pollNow: 'Poll Now',
    recentEmails: 'Recent Emails',
    noMailboxes: 'No mailboxes configured',
    noMailboxesDesc: 'Add a mailbox to start monitoring emails',
    noEmailLogs: 'No emails received yet',
    emailAddress: 'Email address',
    appPassword: 'App password',
    subjectFilter: 'Subject filter (keyword or NONE)',
    telegramTarget: 'Telegram target (chat_id or chat_id:thread_id)',
    monitorSince: 'Monitor since',
    enabled: 'Enabled',
    lastPoll: 'Last poll',
    failures: 'Failures',
    never: 'Never',
    categoryAdobe: 'adobe',
    categoryOnboarding: 'onboarding',
    categoryOffboarding: 'offboarding',
    categoryYandex: 'yandex',
    categoryGeneral: 'general',
    categoryFiltered: 'filtered',
    clearLogs: 'Clear Logs',
    from: 'From',
    sent: 'Sent',
    failed: 'Failed',
    code: 'Code',

    // Common
    failedToLoad: 'Failed to load profile. Please refresh.',
    loading: 'Loading…',
    select: 'Select…',
    inOffice: 'In Office',
    remote: 'Remote',
    draft: 'draft',
    danger: 'danger',
    noAccessTitle: "You don't have access to this page",
    noAccessSubtitle: 'Your role only grants read-only access to the schedule.',

    // Runbooks page
    rbCategoryAccess: 'Access',
    rbCategoryInfra: 'Infra',
    rbCategoryYandex: 'Yandex',
    rbCategoryWebsite: 'Website/CMS',
    rbCategoryOffice: 'Office',
    rbCategoryServices: 'Services',
    rbCopy: 'Copy',
    rbCopied: 'Copied',
    rbRun: 'Run',
    rbLogged: 'Logged',
    rbOwnedBy: 'Owned by',
    rbUpdated: 'Updated',
    rbRunSingle: 'run',
    rbRunPlural: 'runs',
    rbWhenToUse: 'When to use',
    rbProcedure: 'Procedure',
    rbNoContent: 'No content yet',
    rbNoContentDesc: 'Edit this runbook to add steps.',
    rbStepsLabel: 'Steps',
    rbStepTitlePlaceholder: 'Step title',
    rbStepDescPlaceholder: 'Description (optional)',
    rbStepCodePlaceholder: 'Code block (optional)',
    rbAddStep: 'Add step',
    rbEditTitle: 'Edit runbook',
    rbNewTitle: 'New runbook',
    rbCategoryLabel: 'Category',
    rbOwnerLabel: 'Owner',
    rbNoOwner: '— no owner —',
    rbWhenToUsePlaceholder: 'Describe when this runbook should be used…',
    rbTagsLabel: 'Tags (comma-separated)',
    rbTitleRequired: 'Title is required',
    rbSaving: 'Saving…',
    rbSaveChanges: 'Save changes',
    rbCreateRunbook: 'Create runbook',
    rbCreatedToast: 'Runbook created',
    rbSavedToast: 'Runbook saved',
    rbDeleteConfirm: 'Delete this runbook?',
    rbDeletedToast: 'Deleted',
    rbAllRunbooks: 'All runbooks',
    rbSearchPlaceholder: 'Search…',
    rbBrowse: 'Browse',
    rbNotFound: 'No runbooks found',
    rbStepSingular: 'step',
    rbStepPlural: 'steps',
    rbSelectTitle: 'Select a runbook',
    rbSelectDesc: 'Choose a runbook from the list to view its steps.',

    // Command palette
    cmdPlaceholder: 'Jump to page or search runbooks…',
    cmdNoResults: 'No results for',
    cmdPages: 'Pages',
    cmdRunbooksSection: 'Runbooks',
    cmdNavigate: 'navigate',
    cmdOpen: 'open',
    cmdClose: 'close',
    cmdResultSingular: 'result',
    cmdResultPlural: 'results',
    cmdHintHome: 'Dashboard & overview',
    cmdHintSchedule: 'Shifts & calendar',
    cmdHintMail: 'Email monitoring & routing',
    cmdHintTickets: 'Zammad ticket events',
    cmdHintRunbooks: 'Playbooks & procedures',
    cmdHintTimeoff: 'Leave requests & approvals',
    cmdHintReminders: 'Scheduled reminders',
    cmdHintProfile: 'Profile, 2FA, Telegram link',
    cmdHintAdmin: 'Users, config, audit logs',
  },
  ru: {
    // Nav
    home: 'Главная',
    schedule: 'Расписание',
    reminders: 'Напоминания',
    profile: 'Мой профиль',
    admin: 'Админ',
    signOut: 'Выйти',
    lightMode: 'Светлая тема',
    darkMode: 'Тёмная тема',

    // Login
    signIn: 'Войти',
    username: 'Логин',
    password: 'Пароль',
    signingIn: 'Вход…',
    enterCode: 'Введите код из приложения',
    sixDigitCode: '6-значный код',
    verifying: 'Проверка…',
    verify: 'Подтвердить',
    back: '← Назад',
    orDivider: 'или',
    signInSso: 'Войти через SSO',
    ssoErrorNoGroup: 'Ваша учётная запись не состоит ни в одной группе доступа к порталу — обратитесь к администратору.',
    ssoErrorDeactivated: 'Эта учётная запись деактивирована — обратитесь к администратору.',
    ssoErrorGeneric: 'Не удалось войти через SSO — попробуйте снова или используйте пароль.',

    // Notifications
    notifications: 'Уведомления',
    markRead: 'Прочитать',
    clearAll: 'Очистить',
    allClear: 'Всё прочитано',

    // Profile
    myProfile: 'Мой профиль',
    identity: 'Данные',
    displayName: 'Отображаемое имя (видно в расписании)',
    nameColor: 'Цвет имени',
    avatarUrl: 'URL аватара (необязательно)',
    saveIdentity: 'Сохранить',
    timezone: 'Часовой пояс',
    timezoneDesc: 'Все уведомления и время смен отображаются в вашем часовом поясе.',
    yourTimezone: 'Ваш часовой пояс',
    currentLocalTime: 'Текущее местное время',
    saveTimezone: 'Сохранить пояс',
    telegramNotifications: 'Уведомления Telegram',
    linked: 'Привязан',
    notLinked: 'Не привязан',
    telegramUsername: 'Telegram логин',
    shiftNotifications: 'Уведомления о сменах',
    reminderNotifications: 'Уведомления напоминаний',
    saveTelegramSettings: 'Сохранить настройки',
    getLinkCode: 'Получить код привязки',

    // Admin
    adminPanel: 'Панель администратора',
    users: 'Пользователи',
    groups: 'Группы',
    shiftConfig: 'Конфиг смен',
    telegram: 'Telegram',
    notificationsTab: 'Уведомления',
    logs: 'Журнал',
    addUser: '+ Добавить',
    allActions: 'Все действия',
    noLogEntries: 'Нет записей',
    noLogEntriesDesc: 'Действия будут появляться по мере использования портала',

    // Home
    homeEngineerFallback: 'инженер',
    homeAssignedEngineer: 'Назначенный инженер',
    homeNoUpcomingShift: 'Нет ближайшей смены',
    homeMyShifts: 'Мои смены',
    homeOpenMail: 'Открыть почту',
    homeUnchecked: 'не проверено',
    homeBlocked: 'заблокировано',
    homeNext: 'Далее',
    homeNothingScheduled: 'Ничего не запланировано',
    homeCheckNotifications: 'Проверьте уведомления',
    homeAllClear: 'Всё чисто',
    homeNoShiftNextDays: 'Нет смен в ближайшие 5 дней',
    homeOperationalMail: 'Операционная почта',
    homeMailClear: 'Очередь почты пуста',
    homeMailClearDesc: 'Последние синхронизированные письма не требуют разбора.',
    homeIncidents: 'Инциденты:',
    homeIncidentsDesc: 'После интеграции с Grafana здесь будут активные инциденты.',
    homeTickets: 'Тикеты:',
    homeTicketsDesc: 'Синхронизация Zammad покажет нагрузку, SLA-риски и заявки из Telegram.',
    homeRunbooks: 'Ранбуки:',
    homeRunbooksDesc: 'Рекомендации ранбуков появятся после подключения базы знаний.',
    homeTicketsTitle: 'Тикеты',
    homeTicketsOpenFull: 'Все тикеты',
    homeTicketsEmpty: 'Нет активных тикетов',
    homeTicketsLoading: 'Загрузка тикетов…',
    homeAttention: 'Требует внимания',
    homeChecked: 'Проверено',
    homeJustNow: 'только что',
    homeOpenMonitor: 'Открыть мониторинг',
    homeOpenTickets: 'Открыть тикеты',
    homeOpenMailLink: 'Открыть почту',
    homeItems: 'элементов',
    homeMoreDown: 'ещё не отвечают',
    homeOf: 'из',
    homeUpTail: 'работают',
    homeNoDataTail: 'без данных',
    homeSolvedToday: 'решено сегодня',
    homeOnPause: 'на паузе',
    homeNextIn: 'Следующая через',
    homeDay: 'день',
    homeDays: 'дн.',
    homeOnTrack: 'без изменений',
    homeVsLastWk: 'к прошлой нед.',
    homeYourShift: 'Ваша смена',
    homeOnShift: 'На смене',
    homeUntil: 'до',
    homeOffShiftToday: 'Сегодня не на смене',
    homeNextOn: 'Следующая',
    homeYourNextShift: 'Ваша следующая смена',
    homeOnNow: 'Сейчас на смене',
    homeNextUp: 'Следующий',
    homeOpenSchedule: 'Открыть график',
    homeQueueServices: 'Сервисы',
    homeQueueTickets: 'Тикеты',
    homeQueueMail: 'Очередь почты',
    homeAll: 'Все',
    homeAllClear: 'Всё чисто',
    homeServicesClearLine: 'Все цели ответили на последней проверке.',
    homeTicketsClearLine: 'Нерешённых тикетов на доске нет.',
    homeMailClearLine: 'Непроверенных писем в очереди нет.',
    homeRemindersClearLine: 'Ничего не запланировано.',
    homeLastChecked: 'проверено',
    homeDownFor: 'не отвечает',
    homeQuietFor: 'молчит',
    homeMore: 'ещё',
    homeOldest: 'самое старое',
    homeTeamToday: 'Смена сегодня',
    homeNobodyToday: 'На сегодня никто не назначен.',
    homeAdd: 'Добавить',
    homeThisWeek: 'За неделю',
    homeRecapTickets: 'тикетов закрыто',
    homeRecapMail: 'писем обработано',
    homeRecapShifts: 'смен отработано',
    homeScopeMine: 'Мои',
    homeScopeTeam: 'Команда',
    homeNoSubject: '(без темы)',
    homeVAllUp: 'все сервисы работают',
    homeVNoTickets: 'открытых тикетов нет',
    homeVMailClear: 'очередь почты пуста',
    homeVAnd: 'и',
    homeVOnShift: 'вы на смене до',
    homeVOffShift: 'сегодня вы не на смене',
    homePlSvcDown1: 'сервис не отвечает',
    homePlSvcDown2: 'сервиса не отвечают',
    homePlSvcDown5: 'сервисов не отвечают',
    homePlTicketOpen1: 'тикет открыт',
    homePlTicketOpen2: 'тикета открыто',
    homePlTicketOpen5: 'тикетов открыто',
    homePlMailUnchecked1: 'письмо не проверено',
    homePlMailUnchecked2: 'письма не проверено',
    homePlMailUnchecked5: 'писем не проверено',
    homeStatusNoReply: 'нет ответа',
    homeStatusNoData: 'нет данных',
    homeAttnNone: 'нет',
    aiTitle: 'Ассистент',
    aiScope: 'смены · отпуск · ранбуки · обзор почты',
    aiHello: 'Мяу! Я ассистент портала. Умею:\n* **Расписание** — ваши смены и кто дежурит\n* **Отпуска** — проверить заявки или оформить отпуск/отгул (уйдёт на согласование админу)\n* **Ранбуки** — найти инструкцию, создать черновик из кейса («проверь тикет 82505 и сделай ранбук») или с нуля — просто опишите решённую проблему\n* **Обзор почты** — «что мы упустили за неделю?», письма на паузе, онбординги\n* **Итоги** — «что мы сделали за неделю?»: решённые письма, закрытые тикеты, бэкапы ящиков\n* **Передача смены** — напишите `/handover`, я задам 3 коротких вопроса по одному (или пришлите всё сразу одним текстом); сам пост всегда на английском\n\nСпрашивайте на русском или английском!',
    aiPlaceholder: 'Спросите про смены, отпуск, ранбуки…',
    aiThinking: 'Думаю…',
    // Mail page chrome
    mailInbox: 'Входящие',
    mailUnrouted: 'Без категории',
    mailArchive: 'Архив',
    mailSentFolder: 'Отправленные',
    mailCategories: 'Категории',
    mailMailboxes: 'Почтовые ящики',
    mailStatusUnchecked: 'Не проверено',
    mailStatusSolved: 'Решено',
    mailStatusPaused: 'Пауза',
    mailStatusBlocked: 'Блок',
    mailNoMessages: 'Нет писем',
    mailNoMessagesDesc: 'Попробуйте другую папку или зайдите позже',
    mailSelectEmail: 'Выберите письмо',
    mailSelectEmailDesc: 'Нажмите на письмо в списке, чтобы увидеть детали и историю',
    mailGeneral: 'Общее',
    mailFrom: 'От',
    mailMailboxLbl: 'Ящик',
    mailReceived: 'Получено',
    mailMessageBody: 'Текст письма',
    mailActivity: 'Активность и комментарии',
    mailLoadingHistory: 'Загрузка истории…',
    mailNoComments: 'Комментариев пока нет.',
    mailWriteComment: 'Написать комментарий…',
    mailPostComment: 'Отправить',
    mailSaving: 'Сохранение…',
    mailReplied: 'Отвечено',
    mailSentNothing: 'Пока ничего не отправлено',
    mailSentNothingDesc: 'Ответы, отправленные из портала, появятся здесь',
    mailSentTag: 'Отправлено',
    mailFailedTag: 'Ошибка',
    mailLoading: 'Загрузка…',
    // Email replies (SMTP)
    erTitle: 'Ответы по почте',
    erReplyBtn: 'Ответить письмом',
    erPlaceholder: 'Напишите ответ…',
    erHintFrom: 'Отправит настоящее письмо с',
    erHintTo: 'на',
    erCancel: 'Отмена',
    erSend: 'Отправить',
    erSending: 'Отправка…',
    erConfirm: 'Отправить этот ответ на',
    // Tickets page chrome
    tpSubtitle: 'Тикеты Zammad, статусы и комментарии — синхронизация через вебхуки',
    tpTabBoard: 'Тикеты',
    tpTabEvents: 'Журнал событий',
    tpAll: 'Все',
    tpOpen: 'Открытые',
    tpPaused: 'На паузе',
    tpClosed: 'Закрытые',
    tpSearch: 'Поиск: №, тема, исполнитель, клиент…',
    tpNoTickets: 'Тикетов нет',
    tpNoTicketsDesc: 'Тикеты появятся из вебхуков Zammad и периодической синхронизации',
    tpNoEvents: 'Событий пока нет',
    tpNoEventsDesc: 'События появятся, когда Zammad отправит вебхуки',
    tpColTicket: 'Тикет',
    tpColTitle: 'Тема',
    tpColState: 'Статус',
    tpColAssignee: 'Исполнитель',
    tpColCustomer: 'Клиент',
    tpColComments: 'Комм.',
    tpColUpdated: 'Обновлён',
    tpColEvent: 'Событие',
    tpColReceived: 'Получено',
    tpViewJson: 'JSON →',
    tpShowing: 'Показано',
    tpOf: 'из',
    tpPrev: '← Назад',
    tpNext: 'Вперёд →',
    // Alerts page
    // ── Статус сервисов ──
    stTitle: 'Статус сервисов',
    stSubtitle: 'Живые проверки blackbox, поток из Prometheus',
    stInstance: 'Адрес',
    stStatus: 'Статус',
    stCode: 'Код',
    stTls: 'TLS',
    stCert: 'Сертификат',
    stProbe: 'Проверка',
    stDns: 'DNS',
    stAge: 'Обновлено',
    stUp: 'РАБОТАЕТ',
    stDown: 'НЕ ОТВЕЧАЕТ',
    stStale: 'УСТАРЕЛО',
    stDownTile: 'Не отвечают',
    st5xx: 'HTTP 5xx',
    stCerts7d: 'Сертификаты < 7д',
    stStaleTile: 'Устарели',
    stAvgLatency: 'Сред. задержка',
    stAllStale: 'Нет свежих данных ни по одной цели — Prometheus перестал отправлять данные в портал.',
    stNoData: 'Данных проверок пока нет',
    stNoDataDesc: 'Направьте remote_write из Prometheus на /api/status/remote-write, чтобы наполнить таблицу.',
    tkEvOpened: 'Открыт', tkEvAssigned: 'Назначен', tkEvComment: 'Комментарий',
    tkEvClosed: 'Закрыт', tkEvPaused: 'Пауза', tkEvStatus: 'Статус', tkEvSync: 'Синхр.',

    tkInStatus: 'в статусе',
    tkTicket: 'Тикет',
    tkLoading: 'Загрузка…',
    tkOpenBot: 'Открыть бота',
    tkAssignee: 'Исполнитель',
    tkCustomer: 'Клиент',
    tkRequestType: 'Тип запроса',
    tkDescription: 'Описание',
    tkCreated: 'Создан',
    tkUpdated: 'Обновлён',
    tkComments: 'Комментарии',
    tkNoComments: 'Комментариев пока нет.',
    tkEventHistory: 'События',
    tkNoEvents: 'Событий пока нет.',
    tkInternalNote: 'Внутренняя заметка',
    tkNotePlaceholder: 'Написать заметку…',
    tkNoteHint: 'Только на портале — клиенту ничего не отправляется',
    tkAddNote: 'Добавить заметку',
    tkSending: 'Отправка…',
    tkPortalOnly: 'Внутренняя · только портал',
    tkCustomerTag: 'клиент',
    tkStateNew: 'Новый',
    tkStateOpen: 'Открыт',
    tkStateInProgress: 'В работе',
    tkStateOnPause: 'На паузе',
    tkStateClosed: 'Закрыт',

    // Schedule
    schedule_title: 'Расписание',
    day: 'День',
    week: 'Неделя',
    month: 'Месяц',
    today: 'Сегодня',
    timeOff: 'Отгул',
    addShift: '+ Смена',
    generate: 'Генерировать',
    publish: 'Опубликовать',
    timeOffRequests: 'Заявки на отгул',
    noRequests: 'Заявок нет',
    generateSchedule: 'Генерация расписания',
    start: 'Начало',
    end: 'Конец',
    shiftTypes: 'Типы смен',
    cancel: 'Отмена',
    edit: 'Редактировать',
    cmEdited: '(изменено)',
    cmDeleteConfirm: 'Удалить этот комментарий?',
    toolMailboxBackup: 'Бэкап почтового ящика',
    toolMbSubtitle: 'Резервная копия ящика Яндекса по IMAP в сжатый архив на S3 (плюс .mbox по папкам). Пароль используется один раз и нигде не сохраняется.',
    toolEmailLbl: 'Адрес ящика',
    toolPasswordLbl: 'Пароль приложения',
    toolMbHint: 'Требования: на ящике включён доступ по IMAP и есть пароль приложения (создаётся в настройках Яндекс ID).',
    toolBatchPlaceholder: 'user@viory.video:пароль-приложения\n# больше строк = больше ящиков, бэкап по очереди',
    toolStartBackup: 'Начать бэкап',
    toolStarted: 'Бэкап запущен',
    toolBatchLbl: 'Ящики — по одному в строке: email:пароль',
    toolBatchParsed: 'ящик(ов) готово',
    toolBatchBadLines: 'Нераспознанные строки',
    toolBatchEmpty: 'Укажите хотя бы один ящик',
    toolJobs: 'Задачи бэкапа',
    toolNoJobs: 'Бэкапов пока нет',
    toolNotConfigured: 'Инструмент не настроен',
    toolNotConfiguredDesc: 'Не заданы реквизиты S3-хранилища — попросите администратора добавить их в окружение сервера.',
    toolMessages: 'Письма',
    toolFolders: 'папок',
    toolArchive: 'Архив',
    toolDuration: 'Длительность',
    toolSt_queued: 'В очереди',
    toolSt_running: 'Выполняется',
    toolSt_success: 'Успешно',
    toolSt_failed: 'Ошибка',
    toolSt_canceled: 'Отменён',
    toolCancel: 'Отменить',
    toolCancelConfirm: 'Отменить бэкап {email}? Прогресс будет потерян.',
    toolCanceled: 'Бэкап отменён',
    toolPhQueued: 'В очереди…',
    toolPhConnecting: 'Подключение к IMAP…',
    toolPhListing: 'Подсчёт папок и писем…',
    toolPhFetching: 'Скачивание писем',
    toolPhReconnecting: 'Обрыв связи — переподключение…',
    toolEtaLbl: 'осталось',
    toolPrev: 'Назад',
    toolNext: 'Далее',
    toolPageOf: 'Стр. {page} из {total}',
    toolPhArchiving: 'Сжатие архива…',
    toolPhHashing: 'Подсчёт контрольной суммы…',
    toolPhUploading: 'Загрузка на S3…',
    toolPhVerifying: 'Проверка загрузки…',
    toolPhMbox: 'Экспорт .mbox…',
    invFieldClass: 'Класс',
    invClassHardware: 'Оборудование',
    invClassSoftware: 'ПО',
    invClassSubscription: 'Подписки',
    invDeviceTitle: 'Устройство',
    invSectionDevice: 'Устройство',
    invSectionProcurement: 'Закупка',
    invSectionHolder: 'Выдано',
    invSectionComments: 'Комментарии',
    invFieldManufacturer: 'Производитель',
    invFieldLocation: 'Расположение',
    invFieldRack: 'Стойка',
    invFieldTenant: 'Компания',
    invFieldPrimaryIp: 'Основной IP',
    invFieldSupplier: 'Поставщик',
    invFieldInvoiceNo: 'Счёт №',
    invFieldDeliveryDate: 'Доставлено',
    invFieldNetPrice: 'Цена без НДС',
    invFieldInvoice: 'Счёт',
    invFieldKitParent: 'В составе',
    invFieldSignedBy: 'Подписал',
    invFieldHandover: 'Акт передачи',
    invNoHolder: 'Никому не выдано.',
    invOpenInNetbox: 'Открыть в NetBox',
    invOpenFile: 'Открыть файл',
    invEdit: 'Редактировать',
    invTitle: 'Инвентаризация',
    invSubtitle: 'Просмотр и редактирование устройств в NetBox. Удаление отсюда недоступно.',
    invNotConfigured: 'Инвентаризация не настроена',
    invNotConfiguredDesc: 'Отсутствуют URL/токен NetBox — попросите администратора задать их в окружении сервера.',
    invSearch: 'Поиск',
    invSearchPlaceholder: 'Имя, серийник, инв. метка...',
    invSearchBtn: 'Найти',
    invFilterAll: 'Все',
    invNewDevice: 'Новое устройство',
    invEditDevice: 'Редактировать устройство',
    invNoDevices: 'Устройства не найдены',
    invSaved: 'Устройство сохранено',
    invSelectPlaceholder: 'Выбрать…',
    invFieldName: 'Название',
    invFieldType: 'Тип',
    invFieldRole: 'Роль',
    invFieldSite: 'Площадка',
    invFieldStatus: 'Статус',
    invFieldSerial: 'Серийный номер',
    invFieldAssetTag: 'Инв. метка',
    invFieldComments: 'Комментарий',
    handoverTitle: 'Акт передачи оборудования',
    handoverSubtitle: 'Заполните форму передачи оборудования и сформируйте PDF для подписи.',
    handoverEmployee: 'ФИО сотрудника',
    handoverPosition: 'Должность',
    handoverPeriod: 'Период',
    handoverPeriodPlaceholder: 'например, бессрочно, либо диапазон дат',
    handoverPurpose: 'Назначение',
    handoverDate: 'Дата',
    handoverDevices: 'Устройства',
    handoverAddDevice: 'Добавить устройство',
    handoverRemoveDevice: 'Удалить',
    handoverDescription: 'Описание',
    handoverQty: 'Кол-во',
    handoverSerial: 'Серийный номер',
    handoverInvNo: 'Инв. номер',
    handoverComments: 'Комментарий',
    handoverGenerate: 'Сформировать акт',
    handoverAdditionalInfo: 'Доп. информация',
    handoverAccessories: 'Аксессуары',
    handoverGenerated: 'PDF акта передачи сформирован',
    addShiftManually: 'Добавить смену вручную',
    engineer: 'Инженер',
    date: 'Дата',
    shiftType: 'Тип смены',
    location: 'Место',
    add: 'Добавить',
    requestTimeOff: 'Запрос отгула',
    type: 'Тип',
    comment: 'Комментарий',
    submit: 'Отправить',
    dayOff: 'Выходной',
    vacation: 'Отпуск',
    sickLeave: 'Больничный',
    shift_day: 'День',
    shift_night: 'Ночь',
    shift_office: 'Офис',
    schedulePublished: 'опубликовано',
    scheduleDraft: 'черновик',
    scheduleWeekOf: 'Неделя',
    scheduleShortStaffed: 'не хватает людей',
    scheduleCoverageThisWeek: 'Покрытие недели',
    scheduleTimeOffPanel: 'Отгулы',
    scheduleRequest: 'Запросить',
    scheduleNoTimeOff: 'В этом диапазоне нет отгулов',
    scheduleNoCoverage: 'Нет данных по покрытию за этот период',
    scheduleConflictBanner: '{{date}} смена {{shift}}: {{count}} инженер в утверждённом отпуске. Стоит переназначить.',
    scheduleConflictBannerMany: '{{date}} смена {{shift}}: {{count}} инженера(ов) в утверждённом отпуске. Стоит переназначить.',
    scheduleSuggest: 'Предложить',
    scheduleResolve: 'Закрыть',
    scheduleClearDrafts: 'Очистить черновики',
    scheduleGenerated: 'Расписание сгенерировано!',
    scheduleNoDrafts: 'В этом диапазоне нет черновиков',
    scheduleDeleteDraftsConfirm: 'Удалить {{count}} черновых смен из текущего вида?',
    scheduleClearedDrafts: 'Удалено черновиков: {{count}}',
    scheduleShiftAdded: 'Смена добавлена',
    scheduleTimeOffRequested: 'Заявка отправлена',
    scheduleDeleteShiftConfirm: 'Удалить этот черновик смены?',
    scheduleStageForRemovalConfirm: 'Смена опубликована. Она будет помечена для удаления и скрыта от инженеров до следующей публикации.',
    scheduleStagedForRemoval: 'Помечена для удаления',
    scheduleUndoRemoval: 'Отменить удаление',
    scheduleDeleteTimeOffConfirm: 'Удалить эту заявку на отгул?',
    scheduleEditShift: 'Редактировать смену',
    scheduleNotes: 'Заметки',
    scheduleNotesPlaceholder: 'Необязательные заметки…',
    schedulePublishedVisible: 'Опубликовано (видно инженерам)',
    scheduleResetPending: 'Вернуть в ожидание',
    adminBlockedDates: 'Заблокированные даты',
    adminBlockedDatesDesc: 'Даты, на которые этого инженера нельзя назначить на смену',
    adminBlockedDatesEmpty: 'Нет заблокированных дат',
    adminBlockedDatesAdd: 'Заблокировать даты',
    adminBlockedDatesReason: 'Причина (необязательно)',
    save: 'Сохранить',
    delete: 'Удалить',
    reject: 'Отклонить',
    approve: 'Одобрить',
    open: 'Открыть',

    // Reminders
    reminders_title: 'Напоминания',
    active: 'Активные',
    all: 'Все',
    newReminder: '+ Создать',
    noReminders: 'Нет напоминаний',
    noRemindersDesc: 'Создайте первое напоминание',
    cancelReminder: 'Отменить',
    newReminderTitle: 'Новое напоминание',
    title: 'Заголовок',
    description: 'Описание',
    quickSet: 'Быстрый выбор',
    remindAt: 'Напомнить в',
    recurring: 'Повторять',
    telegram: 'Telegram',
    create: 'Создать',
    tomorrow: 'Завтра',

    // OTP
    twoFactor: 'Двухфакторная аутентификация',
    twoFactorDesc: 'Защитите аккаунт с помощью приложения (Google Authenticator, Authy и др.).',
    otpActive: '2FA включена',
    otpInactive: '2FA отключена',
    setupOtp: 'Настроить 2FA',
    otpScanQr: 'Отсканируйте QR-код в приложении-аутентификаторе, затем введите 6-значный код для подтверждения.',
    otpManualKey: 'Ручной ключ',
    otpEnterCode: '6-значный код',
    otpConfirm: 'Подтвердить и включить',
    otpEnabled: '2FA успешно включена',
    otpDisable: 'Отключить 2FA',
    otpDisableDesc: 'Введите код из приложения для отключения 2FA.',
    otpDisabled: '2FA отключена',

    // Time Off Page
    timeOffRequests: 'Выходные',
    timeOffDesc: 'Отпуска, больничные и выходные дни',
    noRequestsDesc: 'Заявок нет',
    timeOffRequested: 'Заявка отправлена!',

    // Telegram
    unlinkTelegram: 'Отвязать',
    telegramUnlinked: 'Telegram отвязан',

    // Mail Reporter
    mailReporter: 'Почта',
    mailboxes: 'Ящики',
    addMailbox: '+ Добавить ящик',
    editMailbox: 'Изменить ящик',
    deleteMailbox: 'Удалить ящик',
    testConnection: 'Проверить',
    pollNow: 'Проверить сейчас',
    recentEmails: 'Последние письма',
    noMailboxes: 'Нет настроенных ящиков',
    noMailboxesDesc: 'Добавьте ящик для мониторинга писем',
    noEmailLogs: 'Писем ещё не получено',
    emailAddress: 'Email адрес',
    appPassword: 'Пароль приложения',
    subjectFilter: 'Фильтр темы (ключевое слово или NONE)',
    telegramTarget: 'Telegram цель (chat_id или chat_id:thread_id)',
    monitorSince: 'Мониторить с',
    enabled: 'Включён',
    lastPoll: 'Последняя проверка',
    failures: 'Ошибок',
    never: 'Никогда',
    categoryAdobe: 'adobe',
    categoryOnboarding: 'онбординг',
    categoryOffboarding: 'оффбординг',
    categoryYandex: 'яндекс',
    categoryGeneral: 'общее',
    categoryFiltered: 'отфильтровано',
    clearLogs: 'Очистить',
    from: 'От',
    sent: 'Отправлено',
    failed: 'Ошибка',
    code: 'Код',

    // Common
    failedToLoad: 'Не удалось загрузить профиль. Обновите страницу.',
    loading: 'Загрузка…',
    select: 'Выбрать…',
    inOffice: 'В офисе',
    remote: 'Удалённо',
    draft: 'черновик',
    noAccessTitle: 'У вас нет доступа к этой странице',
    noAccessSubtitle: 'Ваша роль даёт доступ только на чтение к расписанию.',

    // Runbooks page
    rbCategoryAccess: 'Доступ',
    rbCategoryInfra: 'Инфра',
    rbCategoryYandex: 'Яндекс',
    rbCategoryWebsite: 'Сайт/CMS',
    rbCategoryOffice: 'Офис',
    rbCategoryServices: 'Сервисы',
    rbCopy: 'Копировать',
    rbCopied: 'Скопировано',
    rbRun: 'Запустить',
    rbLogged: 'Выполнено',
    rbOwnedBy: 'Владелец:',
    rbUpdated: 'Обновлено',
    rbRunSingle: 'запуск',
    rbRunPlural: 'запусков',
    rbWhenToUse: 'Когда использовать',
    rbProcedure: 'Процедура',
    rbNoContent: 'Нет содержимого',
    rbNoContentDesc: 'Отредактируйте ранбук, чтобы добавить шаги.',
    rbStepsLabel: 'Шаги',
    rbStepTitlePlaceholder: 'Заголовок шага',
    rbStepDescPlaceholder: 'Описание (необязательно)',
    rbStepCodePlaceholder: 'Код (необязательно)',
    rbAddStep: 'Добавить шаг',
    rbEditTitle: 'Редактировать ранбук',
    rbNewTitle: 'Новый ранбук',
    rbCategoryLabel: 'Категория',
    rbOwnerLabel: 'Владелец',
    rbNoOwner: '— без владельца —',
    rbWhenToUsePlaceholder: 'Опишите, когда использовать этот ранбук…',
    rbTagsLabel: 'Теги (через запятую)',
    rbTitleRequired: 'Заголовок обязателен',
    rbSaving: 'Сохранение…',
    rbSaveChanges: 'Сохранить изменения',
    rbCreateRunbook: 'Создать ранбук',
    rbCreatedToast: 'Ранбук создан',
    rbSavedToast: 'Ранбук сохранён',
    rbDeleteConfirm: 'Удалить этот ранбук?',
    rbDeletedToast: 'Удалено',
    rbAllRunbooks: 'Все ранбуки',
    rbSearchPlaceholder: 'Поиск…',
    rbBrowse: 'Просмотр',
    rbNotFound: 'Ранбуки не найдены',
    rbStepSingular: 'шаг',
    rbStepPlural: 'шагов',
    rbSelectTitle: 'Выберите ранбук',
    rbSelectDesc: 'Выберите ранбук из списка, чтобы увидеть шаги.',

    // Command palette
    cmdPlaceholder: 'Перейти на страницу или найти ранбук…',
    cmdNoResults: 'Нет результатов для',
    cmdPages: 'Страницы',
    cmdRunbooksSection: 'Ранбуки',
    cmdNavigate: 'навигация',
    cmdOpen: 'открыть',
    cmdClose: 'закрыть',
    cmdResultSingular: 'результат',
    cmdResultPlural: 'результатов',
    cmdHintHome: 'Дашборд и обзор',
    cmdHintSchedule: 'Смены и расписание',
    cmdHintMail: 'Мониторинг почты',
    cmdHintTickets: 'Тикеты Zammad',
    cmdHintRunbooks: 'Плейбуки и процедуры',
    cmdHintTimeoff: 'Заявки на отгул',
    cmdHintReminders: 'Напоминания',
    cmdHintProfile: 'Профиль, 2FA, Telegram',
    cmdHintAdmin: 'Пользователи, настройки, журнал',
  },
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  useEffect(() => { localStorage.setItem('lang', lang); }, [lang]);

  const toggle = () => setLang(l => l === 'en' ? 'ru' : 'en');
  const t = key => translations[lang]?.[key] ?? translations.en[key] ?? key;

  return (
    <LangContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() { return useContext(LangContext); }
