import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Nav
    home: 'Home',
    schedule: 'Schedule',
    reminders: 'Reminders',
    profile: 'My Profile',
    admin: 'Admin',
    signOut: 'Sign out',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',

    // Login
    signIn: 'Sign in',
    username: 'Username',
    password: 'Password',
    signingIn: 'Signing in…',
    enterCode: 'Enter authenticator code',
    sixDigitCode: '6-digit code',
    verifying: 'Verifying…',
    verify: 'Verify',
    back: '← Back',

    // Notifications
    notifications: 'Notifications',
    markRead: 'Mark read',
    clearAll: 'Clear all',
    allClear: 'All clear',

    // Profile
    myProfile: 'My Profile',
    identity: 'Identity',
    displayName: 'Display name (shown in schedule)',
    nameColor: 'Name color',
    avatarUrl: 'Avatar URL (optional)',
    saveIdentity: 'Save identity',
    timezone: 'Timezone',
    timezoneDesc: 'All notifications and schedule times are adjusted to your timezone.',
    yourTimezone: 'Your timezone',
    currentLocalTime: 'Your current local time',
    saveTimezone: 'Save timezone',
    telegramNotifications: 'Telegram Notifications',
    linked: 'Linked',
    notLinked: 'Not linked',
    telegramUsername: 'Telegram username',
    shiftNotifications: 'Shift notifications',
    reminderNotifications: 'Reminder notifications',
    saveTelegramSettings: 'Save telegram settings',
    getLinkCode: 'Get link code',

    // Admin
    adminPanel: 'Admin Panel',
    users: 'Users',
    groups: 'Groups',
    shiftConfig: 'Shift Config',
    telegram: 'Telegram',
    notificationsTab: 'Notifications',
    logs: 'Logs',
    addUser: '+ Add user',
    allActions: 'All actions',
    noLogEntries: 'No log entries',
    noLogEntriesDesc: 'Actions will appear here as users interact with the portal',

    // Home
    homeEngineerFallback: 'engineer',
    homeAssignedEngineer: 'Assigned engineer',
    homeNoUpcomingShift: 'No upcoming shift',
    homeNoActiveShift: 'No active shift found for you today',
    homeMailItem: 'mail item',
    homeMailItems: 'mail items',
    homeNeedAttention: 'need attention.',
    homeNoMailItems: 'No unresolved mail items in the latest queue.',
    homeMyShifts: 'My shifts',
    homeOpenMail: 'Open mail',
    homeMailQueue: 'Mail queue',
    homeUnchecked: 'unchecked',
    homeBlocked: 'blocked',
    homeActiveReminders: 'Active reminders',
    homeNext: 'Next',
    homeNothingScheduled: 'Nothing scheduled',
    homeUnreadNotices: 'Unread notices',
    homeCheckNotifications: 'Check notification panel',
    homeAllClear: 'All clear',
    homeNextEngineer: 'Next engineer',
    homeNoShiftNextDays: 'No shift in next 5 days',
    homeOperationalMail: 'Operational mail',
    homeLoadingQueue: 'Loading operational queue…',
    homeMailClear: 'Mail queue is clear',
    homeMailClearDesc: 'Latest synced emails do not need triage.',
    homeShiftContext: 'Shift context',
    homeYou: 'You',
    homeIncidents: 'Incidents:',
    homeIncidentsDesc: 'Grafana alert webhook integration will surface active incidents here.',
    homeTickets: 'Tickets:',
    homeTicketsDesc: 'Zammad sync will show active ticket load, SLA risk, and Telegram-linked cases.',
    homeRunbooks: 'Runbooks:',
    homeRunbooksDesc: 'Runbook recommendations will appear here once the knowledge module is connected.',
    homeTicketsTitle: 'Tickets',
    homeTicketsOpenFull: 'Open full view',
    homeTicketsEmpty: 'No active tickets',
    homeTicketsLoading: 'Loading tickets…',
    homeAttention: 'Needs attention',
    homeAttnAlerts: 'Firing alerts',
    homeAttnTickets: 'Unsolved tickets',
    homeAttnUnchecked: 'Unchecked emails',
    homeAttnEmpty: 'All clear — nothing needs attention',
    homeAttnNone: 'none',
    homeShowAll: 'Show all',
    aiTitle: 'Assistant',
    aiScope: 'schedule · time off · runbooks · mail review',
    aiHello: 'Meow! I\'m the portal assistant. I can:\n* **Schedule** — your shifts and who\'s on duty\n* **Time off** — check requests or file a vacation/day-off (goes to admin approval)\n* **Runbooks** — find the right guide for "how do I…" questions\n* **Mail review** — paused or onboarding emails, “did we miss anything this week?”\n\nAsk me in English or Russian!',
    aiPlaceholder: 'Ask about shifts, time off, runbooks…',
    aiThinking: 'Thinking…',
    // Mail page chrome
    mailInbox: 'Inbox',
    mailUnrouted: 'Unrouted',
    mailArchive: 'Archive',
    mailSentFolder: 'Sent',
    mailCategories: 'Categories',
    mailMailboxes: 'Mailboxes',
    mailStatusUnchecked: 'Unchecked',
    mailStatusSolved: 'Solved',
    mailStatusPaused: 'Paused',
    mailStatusBlocked: 'Blocked',
    mailNoMessages: 'No messages',
    mailNoMessagesDesc: 'Try another folder or check back later',
    mailSelectEmail: 'Select an email',
    mailSelectEmailDesc: 'Click on a message from the list to view its details and history',
    mailGeneral: 'General',
    mailFrom: 'From',
    mailMailboxLbl: 'Mailbox',
    mailReceived: 'Received',
    mailMessageBody: 'Message Body',
    mailActivity: 'Activity & Comments',
    mailLoadingHistory: 'Loading history…',
    mailNoComments: 'No comments yet.',
    mailWriteComment: 'Write a comment…',
    mailPostComment: 'Post Comment',
    mailSaving: 'Saving…',
    mailReplied: 'Replied',
    mailSentNothing: 'Nothing sent yet',
    mailSentNothingDesc: 'Replies sent from the portal will appear here',
    mailSentTag: 'Sent',
    mailFailedTag: 'Failed',
    mailLoading: 'Loading…',
    // Email replies (SMTP)
    erTitle: 'Email replies',
    erReplyBtn: 'Reply by email',
    erPlaceholder: 'Write your reply…',
    erHintFrom: 'Sends a real email from',
    erHintTo: 'to',
    erCancel: 'Cancel',
    erSend: 'Send reply',
    erSending: 'Sending…',
    erConfirm: 'Send this email reply to',
    // Tickets page chrome
    tpSubtitle: 'Zammad tickets, statuses and comments — synced live via webhooks',
    tpTabBoard: 'Tickets',
    tpTabEvents: 'Event log',
    tpAll: 'All',
    tpOpen: 'Open',
    tpPaused: 'Paused',
    tpClosed: 'Closed',
    tpSearch: 'Search #, title, assignee, customer…',
    tpNoTickets: 'No tickets',
    tpNoTicketsDesc: 'Tickets appear here from Zammad webhooks and periodic sync',
    tpNoEvents: 'No events yet',
    tpNoEventsDesc: 'Events appear once Zammad sends webhooks',
    tpColTicket: 'Ticket',
    tpColTitle: 'Title',
    tpColState: 'State',
    tpColAssignee: 'Assignee',
    tpColCustomer: 'Customer',
    tpColComments: 'Cmts',
    tpColUpdated: 'Updated',
    tpColEvent: 'Event',
    tpColReceived: 'Received',
    tpViewJson: 'View JSON →',
    tpShowing: 'Showing',
    tpOf: 'of',
    tpPrev: '← Prev',
    tpNext: 'Next →',
    // Alerts page
    alTitle: 'Alerts',
    alSubtitle: 'Grafana alerts — delivered live via the alerting webhook',
    alAll: 'All',
    alFiring: 'Firing',
    alResolved: 'Resolved',
    alNoAlerts: 'No alerts',
    alNoAlertsDesc: 'Alerts appear here once Grafana sends webhooks',
    alFiringFor: 'firing for',
    alResolvedAt: 'resolved',
    alFiredTimes: 'fired',
    tkEvOpened: 'Opened', tkEvAssigned: 'Assigned', tkEvComment: 'Comment',
    tkEvClosed: 'Closed', tkEvPaused: 'Paused', tkEvStatus: 'Status', tkEvSync: 'Sync',

    tkInStatus: 'in status',
    tkTicket: 'Ticket',
    tkLoading: 'Loading…',
    tkOpenBot: 'Open Bot',
    tkAssignee: 'Assignee',
    tkCustomer: 'Customer',
    tkRequestType: 'Request type',
    tkDescription: 'Description',
    tkCreated: 'Created',
    tkUpdated: 'Updated',
    tkComments: 'Comments',
    tkNoComments: 'No comments yet.',
    tkEventHistory: 'Events',
    tkNoEvents: 'No events yet.',
    tkInternalNote: 'Internal note',
    tkNotePlaceholder: 'Write a note…',
    tkNoteHint: 'Portal only — nothing is sent to the customer',
    tkAddNote: 'Add note',
    tkSending: 'Sending…',
    tkPortalOnly: 'Internal · portal only',
    tkCustomerTag: 'customer',
    tkStateNew: 'New',
    tkStateOpen: 'Open',
    tkStateInProgress: 'In progress',
    tkStateOnPause: 'On pause',
    tkStateClosed: 'Closed',

    // Schedule
    schedule_title: 'Schedule',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    today: 'Today',
    timeOff: 'Time off',
    addShift: '+ Shift',
    generate: 'Generate',
    publish: 'Publish',
    timeOffRequests: 'Time-off requests',
    noRequests: 'No requests',
    generateSchedule: 'Generate Schedule',
    start: 'Start',
    end: 'End',
    shiftTypes: 'Shift types',
    cancel: 'Cancel',
    addShiftManually: 'Add Shift Manually',
    engineer: 'Engineer',
    date: 'Date',
    shiftType: 'Shift type',
    location: 'Location',
    add: 'Add',
    requestTimeOff: 'Request Time Off',
    type: 'Type',
    comment: 'Comment',
    submit: 'Submit',
    dayOff: 'Day off',
    vacation: 'Vacation',
    sickLeave: 'Sick leave',
    shift_day: 'Day',
    shift_night: 'Night',
    shift_office: 'Office',
    schedulePublished: 'published',
    scheduleDraft: 'draft',
    scheduleWeekOf: 'Week of',
    scheduleShortStaffed: 'short staffed',
    scheduleCoverageThisWeek: 'Coverage this week',
    scheduleTimeOffPanel: 'Time-off',
    scheduleRequest: 'Request',
    scheduleNoTimeOff: 'No time-off in this range',
    scheduleNoCoverage: 'No coverage data for this range',
    scheduleConflictBanner: '{{date}} {{shift}} shift has {{count}} engineer on approved leave. Consider reassigning.',
    scheduleConflictBannerMany: '{{date}} {{shift}} shift has {{count}} engineers on approved leave. Consider reassigning.',
    scheduleSuggest: 'Suggest',
    scheduleResolve: 'Resolve',
    scheduleClearDrafts: 'Clear drafts',
    scheduleGenerated: 'Schedule generated!',
    scheduleNoDrafts: 'No drafts in this range',
    scheduleDeleteDraftsConfirm: 'Delete {{count}} draft shift(s) from this view?',
    scheduleClearedDrafts: 'Cleared {{count}} draft(s)',
    scheduleShiftAdded: 'Shift added',
    scheduleTimeOffRequested: 'Time-off requested',
    scheduleDeleteShiftConfirm: 'Delete this draft shift?',
    scheduleStageForRemovalConfirm: 'This shift is published. It will be staged for removal and hidden from engineers until you click Publish.',
    scheduleStagedForRemoval: 'Staged for removal',
    scheduleUndoRemoval: 'Undo removal',
    scheduleDeleteTimeOffConfirm: 'Delete this time-off request?',
    scheduleEditShift: 'Edit Shift',
    scheduleNotes: 'Notes',
    scheduleNotesPlaceholder: 'Optional notes…',
    schedulePublishedVisible: 'Published (visible to engineers)',
    scheduleResetPending: 'Reset to pending',
    adminBlockedDates: 'Blocked Dates',
    adminBlockedDatesDesc: 'Dates this engineer cannot be assigned shifts',
    adminBlockedDatesEmpty: 'No blocked dates',
    adminBlockedDatesAdd: 'Block dates',
    adminBlockedDatesReason: 'Reason (optional)',
    save: 'Save',
    delete: 'Delete',
    reject: 'Reject',
    approve: 'Approve',
    open: 'Open',

    // Reminders
    reminders_title: 'Reminders',
    active: 'Active',
    all: 'All',
    newReminder: '+ New',
    noReminders: 'No reminders',
    noRemindersDesc: 'Create one to get started',
    cancelReminder: 'Cancel',
    newReminderTitle: 'New Reminder',
    title: 'Title',
    description: 'Description',
    quickSet: 'Quick set',
    remindAt: 'Remind at',
    recurring: 'Recurring',
    telegram: 'Telegram',
    create: 'Create',
    tomorrow: 'Tomorrow',

    // OTP
    twoFactor: 'Two-Factor Authentication',
    twoFactorDesc: 'Protect your account with an authenticator app (Google Authenticator, Authy, etc.).',
    otpActive: '2FA enabled',
    otpInactive: '2FA disabled',
    setupOtp: 'Set up 2FA',
    otpScanQr: 'Scan this QR code with your authenticator app, then enter the 6-digit code to confirm.',
    otpManualKey: 'Manual key',
    otpEnterCode: '6-digit code',
    otpConfirm: 'Confirm & enable',
    otpEnabled: '2FA enabled successfully',
    otpDisable: 'Disable 2FA',
    otpDisableDesc: 'Enter your current authenticator code to disable 2FA.',
    otpDisabled: '2FA has been disabled',

    // Time Off Page
    timeOffRequests: 'Time Off',
    timeOffDesc: 'Manage vacation, sick leave, and days off',
    noRequestsDesc: 'No requests found',
    timeOffRequested: 'Time-off requested!',

    // Telegram
    unlinkTelegram: 'Unlink',
    telegramUnlinked: 'Telegram unlinked',

    // Mail Reporter
    mailReporter: 'Mail Reporter',
    mailboxes: 'Mailboxes',
    addMailbox: '+ Add Mailbox',
    editMailbox: 'Edit Mailbox',
    deleteMailbox: 'Delete Mailbox',
    testConnection: 'Test Connection',
    pollNow: 'Poll Now',
    recentEmails: 'Recent Emails',
    noMailboxes: 'No mailboxes configured',
    noMailboxesDesc: 'Add a mailbox to start monitoring emails',
    noEmailLogs: 'No emails received yet',
    emailAddress: 'Email address',
    appPassword: 'App password',
    subjectFilter: 'Subject filter (keyword or NONE)',
    telegramTarget: 'Telegram target (chat_id or chat_id:thread_id)',
    monitorSince: 'Monitor since',
    enabled: 'Enabled',
    lastPoll: 'Last poll',
    failures: 'Failures',
    never: 'Never',
    categoryAdobe: 'adobe',
    categoryOnboarding: 'onboarding',
    categoryOffboarding: 'offboarding',
    categoryYandex: 'yandex',
    categoryGeneral: 'general',
    categoryFiltered: 'filtered',
    clearLogs: 'Clear Logs',
    from: 'From',
    sent: 'Sent',
    failed: 'Failed',
    code: 'Code',

    // Common
    failedToLoad: 'Failed to load profile. Please refresh.',
    loading: 'Loading…',
    select: 'Select…',
    inOffice: 'In Office',
    remote: 'Remote',
    draft: 'draft',
    danger: 'danger',

    // Runbooks page
    rbCategoryAccess: 'Access',
    rbCategoryInfra: 'Infra',
    rbCategoryYandex: 'Yandex',
    rbCategoryWebsite: 'Website/CMS',
    rbCategoryOffice: 'Office',
    rbCopy: 'Copy',
    rbCopied: 'Copied',
    rbRun: 'Run',
    rbLogged: 'Logged',
    rbOwnedBy: 'Owned by',
    rbUpdated: 'Updated',
    rbRunSingle: 'run',
    rbRunPlural: 'runs',
    rbWhenToUse: 'When to use',
    rbProcedure: 'Procedure',
    rbNoContent: 'No content yet',
    rbNoContentDesc: 'Edit this runbook to add steps.',
    rbStepsLabel: 'Steps',
    rbStepTitlePlaceholder: 'Step title',
    rbStepDescPlaceholder: 'Description (optional)',
    rbStepCodePlaceholder: 'Code block (optional)',
    rbAddStep: 'Add step',
    rbEditTitle: 'Edit runbook',
    rbNewTitle: 'New runbook',
    rbCategoryLabel: 'Category',
    rbOwnerLabel: 'Owner',
    rbNoOwner: '— no owner —',
    rbWhenToUsePlaceholder: 'Describe when this runbook should be used…',
    rbTagsLabel: 'Tags (comma-separated)',
    rbTitleRequired: 'Title is required',
    rbSaving: 'Saving…',
    rbSaveChanges: 'Save changes',
    rbCreateRunbook: 'Create runbook',
    rbCreatedToast: 'Runbook created',
    rbSavedToast: 'Runbook saved',
    rbDeleteConfirm: 'Delete this runbook?',
    rbDeletedToast: 'Deleted',
    rbAllRunbooks: 'All runbooks',
    rbSearchPlaceholder: 'Search…',
    rbBrowse: 'Browse',
    rbNotFound: 'No runbooks found',
    rbStepSingular: 'step',
    rbStepPlural: 'steps',
    rbSelectTitle: 'Select a runbook',
    rbSelectDesc: 'Choose a runbook from the list to view its steps.',

    // Command palette
    cmdPlaceholder: 'Jump to page or search runbooks…',
    cmdNoResults: 'No results for',
    cmdPages: 'Pages',
    cmdRunbooksSection: 'Runbooks',
    cmdNavigate: 'navigate',
    cmdOpen: 'open',
    cmdClose: 'close',
    cmdResultSingular: 'result',
    cmdResultPlural: 'results',
    cmdHintHome: 'Dashboard & overview',
    cmdHintSchedule: 'Shifts & calendar',
    cmdHintMail: 'Email monitoring & routing',
    cmdHintTickets: 'Zammad ticket events',
    cmdHintRunbooks: 'Playbooks & procedures',
    cmdHintTimeoff: 'Leave requests & approvals',
    cmdHintReminders: 'Scheduled reminders',
    cmdHintProfile: 'Profile, 2FA, Telegram link',
    cmdHintAdmin: 'Users, config, audit logs',
  },
  ru: {
    // Nav
    home: 'Главная',
    schedule: 'Расписание',
    reminders: 'Напоминания',
    profile: 'Мой профиль',
    admin: 'Админ',
    signOut: 'Выйти',
    lightMode: 'Светлая тема',
    darkMode: 'Тёмная тема',

    // Login
    signIn: 'Войти',
    username: 'Логин',
    password: 'Пароль',
    signingIn: 'Вход…',
    enterCode: 'Введите код из приложения',
    sixDigitCode: '6-значный код',
    verifying: 'Проверка…',
    verify: 'Подтвердить',
    back: '← Назад',

    // Notifications
    notifications: 'Уведомления',
    markRead: 'Прочитать',
    clearAll: 'Очистить',
    allClear: 'Всё прочитано',

    // Profile
    myProfile: 'Мой профиль',
    identity: 'Данные',
    displayName: 'Отображаемое имя (видно в расписании)',
    nameColor: 'Цвет имени',
    avatarUrl: 'URL аватара (необязательно)',
    saveIdentity: 'Сохранить',
    timezone: 'Часовой пояс',
    timezoneDesc: 'Все уведомления и время смен отображаются в вашем часовом поясе.',
    yourTimezone: 'Ваш часовой пояс',
    currentLocalTime: 'Текущее местное время',
    saveTimezone: 'Сохранить пояс',
    telegramNotifications: 'Уведомления Telegram',
    linked: 'Привязан',
    notLinked: 'Не привязан',
    telegramUsername: 'Telegram логин',
    shiftNotifications: 'Уведомления о сменах',
    reminderNotifications: 'Уведомления напоминаний',
    saveTelegramSettings: 'Сохранить настройки',
    getLinkCode: 'Получить код привязки',

    // Admin
    adminPanel: 'Панель администратора',
    users: 'Пользователи',
    groups: 'Группы',
    shiftConfig: 'Конфиг смен',
    telegram: 'Telegram',
    notificationsTab: 'Уведомления',
    logs: 'Журнал',
    addUser: '+ Добавить',
    allActions: 'Все действия',
    noLogEntries: 'Нет записей',
    noLogEntriesDesc: 'Действия будут появляться по мере использования портала',

    // Home
    homeEngineerFallback: 'инженер',
    homeAssignedEngineer: 'Назначенный инженер',
    homeNoUpcomingShift: 'Нет ближайшей смены',
    homeNoActiveShift: 'Сегодня у вас нет активной смены',
    homeMailItem: 'письмо',
    homeMailItems: 'писем',
    homeNeedAttention: 'требуют внимания.',
    homeNoMailItems: 'В последней очереди нет неразобранных писем.',
    homeMyShifts: 'Мои смены',
    homeOpenMail: 'Открыть почту',
    homeMailQueue: 'Очередь почты',
    homeUnchecked: 'не проверено',
    homeBlocked: 'заблокировано',
    homeActiveReminders: 'Активные напоминания',
    homeNext: 'Далее',
    homeNothingScheduled: 'Ничего не запланировано',
    homeUnreadNotices: 'Новые уведомления',
    homeCheckNotifications: 'Проверьте уведомления',
    homeAllClear: 'Всё чисто',
    homeNextEngineer: 'Следующий инженер',
    homeNoShiftNextDays: 'Нет смен в ближайшие 5 дней',
    homeOperationalMail: 'Операционная почта',
    homeLoadingQueue: 'Загрузка очереди…',
    homeMailClear: 'Очередь почты пуста',
    homeMailClearDesc: 'Последние синхронизированные письма не требуют разбора.',
    homeShiftContext: 'Контекст смены',
    homeYou: 'Вы',
    homeIncidents: 'Инциденты:',
    homeIncidentsDesc: 'После интеграции с Grafana здесь будут активные инциденты.',
    homeTickets: 'Тикеты:',
    homeTicketsDesc: 'Синхронизация Zammad покажет нагрузку, SLA-риски и заявки из Telegram.',
    homeRunbooks: 'Ранбуки:',
    homeRunbooksDesc: 'Рекомендации ранбуков появятся после подключения базы знаний.',
    homeTicketsTitle: 'Тикеты',
    homeTicketsOpenFull: 'Все тикеты',
    homeTicketsEmpty: 'Нет активных тикетов',
    homeTicketsLoading: 'Загрузка тикетов…',
    homeAttention: 'Требует внимания',
    homeAttnAlerts: 'Горящие алерты',
    homeAttnTickets: 'Нерешённые тикеты',
    homeAttnUnchecked: 'Непроверенные письма',
    homeAttnEmpty: 'Всё чисто — внимания ничего не требует',
    homeAttnNone: 'нет',
    homeShowAll: 'Показать все',
    aiTitle: 'Ассистент',
    aiScope: 'смены · отпуск · ранбуки · обзор почты',
    aiHello: 'Мяу! Я ассистент портала. Умею:\n* **Расписание** — ваши смены и кто дежурит\n* **Отпуска** — проверить заявки или оформить отпуск/отгул (уйдёт на согласование админу)\n* **Ранбуки** — найти нужную инструкцию на вопрос «как сделать…»\n* **Обзор почты** — «что мы упустили за неделю?», письма на паузе, онбординги\n\nСпрашивайте на русском или английском!',
    aiPlaceholder: 'Спросите про смены, отпуск, ранбуки…',
    aiThinking: 'Думаю…',
    // Mail page chrome
    mailInbox: 'Входящие',
    mailUnrouted: 'Без категории',
    mailArchive: 'Архив',
    mailSentFolder: 'Отправленные',
    mailCategories: 'Категории',
    mailMailboxes: 'Почтовые ящики',
    mailStatusUnchecked: 'Не проверено',
    mailStatusSolved: 'Решено',
    mailStatusPaused: 'Пауза',
    mailStatusBlocked: 'Блок',
    mailNoMessages: 'Нет писем',
    mailNoMessagesDesc: 'Попробуйте другую папку или зайдите позже',
    mailSelectEmail: 'Выберите письмо',
    mailSelectEmailDesc: 'Нажмите на письмо в списке, чтобы увидеть детали и историю',
    mailGeneral: 'Общее',
    mailFrom: 'От',
    mailMailboxLbl: 'Ящик',
    mailReceived: 'Получено',
    mailMessageBody: 'Текст письма',
    mailActivity: 'Активность и комментарии',
    mailLoadingHistory: 'Загрузка истории…',
    mailNoComments: 'Комментариев пока нет.',
    mailWriteComment: 'Написать комментарий…',
    mailPostComment: 'Отправить',
    mailSaving: 'Сохранение…',
    mailReplied: 'Отвечено',
    mailSentNothing: 'Пока ничего не отправлено',
    mailSentNothingDesc: 'Ответы, отправленные из портала, появятся здесь',
    mailSentTag: 'Отправлено',
    mailFailedTag: 'Ошибка',
    mailLoading: 'Загрузка…',
    // Email replies (SMTP)
    erTitle: 'Ответы по почте',
    erReplyBtn: 'Ответить письмом',
    erPlaceholder: 'Напишите ответ…',
    erHintFrom: 'Отправит настоящее письмо с',
    erHintTo: 'на',
    erCancel: 'Отмена',
    erSend: 'Отправить',
    erSending: 'Отправка…',
    erConfirm: 'Отправить этот ответ на',
    // Tickets page chrome
    tpSubtitle: 'Тикеты Zammad, статусы и комментарии — синхронизация через вебхуки',
    tpTabBoard: 'Тикеты',
    tpTabEvents: 'Журнал событий',
    tpAll: 'Все',
    tpOpen: 'Открытые',
    tpPaused: 'На паузе',
    tpClosed: 'Закрытые',
    tpSearch: 'Поиск: №, тема, исполнитель, клиент…',
    tpNoTickets: 'Тикетов нет',
    tpNoTicketsDesc: 'Тикеты появятся из вебхуков Zammad и периодической синхронизации',
    tpNoEvents: 'Событий пока нет',
    tpNoEventsDesc: 'События появятся, когда Zammad отправит вебхуки',
    tpColTicket: 'Тикет',
    tpColTitle: 'Тема',
    tpColState: 'Статус',
    tpColAssignee: 'Исполнитель',
    tpColCustomer: 'Клиент',
    tpColComments: 'Комм.',
    tpColUpdated: 'Обновлён',
    tpColEvent: 'Событие',
    tpColReceived: 'Получено',
    tpViewJson: 'JSON →',
    tpShowing: 'Показано',
    tpOf: 'из',
    tpPrev: '← Назад',
    tpNext: 'Вперёд →',
    // Alerts page
    alTitle: 'Алерты',
    alSubtitle: 'Алерты Grafana — приходят через вебхук алертинга',
    alAll: 'Все',
    alFiring: 'Горят',
    alResolved: 'Решены',
    alNoAlerts: 'Алертов нет',
    alNoAlertsDesc: 'Алерты появятся, когда Grafana отправит вебхуки',
    alFiringFor: 'горит уже',
    alResolvedAt: 'решён',
    alFiredTimes: 'срабатываний:',
    tkEvOpened: 'Открыт', tkEvAssigned: 'Назначен', tkEvComment: 'Комментарий',
    tkEvClosed: 'Закрыт', tkEvPaused: 'Пауза', tkEvStatus: 'Статус', tkEvSync: 'Синхр.',

    tkInStatus: 'в статусе',
    tkTicket: 'Тикет',
    tkLoading: 'Загрузка…',
    tkOpenBot: 'Открыть бота',
    tkAssignee: 'Исполнитель',
    tkCustomer: 'Клиент',
    tkRequestType: 'Тип запроса',
    tkDescription: 'Описание',
    tkCreated: 'Создан',
    tkUpdated: 'Обновлён',
    tkComments: 'Комментарии',
    tkNoComments: 'Комментариев пока нет.',
    tkEventHistory: 'События',
    tkNoEvents: 'Событий пока нет.',
    tkInternalNote: 'Внутренняя заметка',
    tkNotePlaceholder: 'Написать заметку…',
    tkNoteHint: 'Только на портале — клиенту ничего не отправляется',
    tkAddNote: 'Добавить заметку',
    tkSending: 'Отправка…',
    tkPortalOnly: 'Внутренняя · только портал',
    tkCustomerTag: 'клиент',
    tkStateNew: 'Новый',
    tkStateOpen: 'Открыт',
    tkStateInProgress: 'В работе',
    tkStateOnPause: 'На паузе',
    tkStateClosed: 'Закрыт',

    // Schedule
    schedule_title: 'Расписание',
    day: 'День',
    week: 'Неделя',
    month: 'Месяц',
    today: 'Сегодня',
    timeOff: 'Отгул',
    addShift: '+ Смена',
    generate: 'Генерировать',
    publish: 'Опубликовать',
    timeOffRequests: 'Заявки на отгул',
    noRequests: 'Заявок нет',
    generateSchedule: 'Генерация расписания',
    start: 'Начало',
    end: 'Конец',
    shiftTypes: 'Типы смен',
    cancel: 'Отмена',
    addShiftManually: 'Добавить смену вручную',
    engineer: 'Инженер',
    date: 'Дата',
    shiftType: 'Тип смены',
    location: 'Место',
    add: 'Добавить',
    requestTimeOff: 'Запрос отгула',
    type: 'Тип',
    comment: 'Комментарий',
    submit: 'Отправить',
    dayOff: 'Выходной',
    vacation: 'Отпуск',
    sickLeave: 'Больничный',
    shift_day: 'День',
    shift_night: 'Ночь',
    shift_office: 'Офис',
    schedulePublished: 'опубликовано',
    scheduleDraft: 'черновик',
    scheduleWeekOf: 'Неделя',
    scheduleShortStaffed: 'не хватает людей',
    scheduleCoverageThisWeek: 'Покрытие недели',
    scheduleTimeOffPanel: 'Отгулы',
    scheduleRequest: 'Запросить',
    scheduleNoTimeOff: 'В этом диапазоне нет отгулов',
    scheduleNoCoverage: 'Нет данных по покрытию за этот период',
    scheduleConflictBanner: '{{date}} смена {{shift}}: {{count}} инженер в утверждённом отпуске. Стоит переназначить.',
    scheduleConflictBannerMany: '{{date}} смена {{shift}}: {{count}} инженера(ов) в утверждённом отпуске. Стоит переназначить.',
    scheduleSuggest: 'Предложить',
    scheduleResolve: 'Закрыть',
    scheduleClearDrafts: 'Очистить черновики',
    scheduleGenerated: 'Расписание сгенерировано!',
    scheduleNoDrafts: 'В этом диапазоне нет черновиков',
    scheduleDeleteDraftsConfirm: 'Удалить {{count}} черновых смен из текущего вида?',
    scheduleClearedDrafts: 'Удалено черновиков: {{count}}',
    scheduleShiftAdded: 'Смена добавлена',
    scheduleTimeOffRequested: 'Заявка отправлена',
    scheduleDeleteShiftConfirm: 'Удалить этот черновик смены?',
    scheduleStageForRemovalConfirm: 'Смена опубликована. Она будет помечена для удаления и скрыта от инженеров до следующей публикации.',
    scheduleStagedForRemoval: 'Помечена для удаления',
    scheduleUndoRemoval: 'Отменить удаление',
    scheduleDeleteTimeOffConfirm: 'Удалить эту заявку на отгул?',
    scheduleEditShift: 'Редактировать смену',
    scheduleNotes: 'Заметки',
    scheduleNotesPlaceholder: 'Необязательные заметки…',
    schedulePublishedVisible: 'Опубликовано (видно инженерам)',
    scheduleResetPending: 'Вернуть в ожидание',
    adminBlockedDates: 'Заблокированные даты',
    adminBlockedDatesDesc: 'Даты, на которые этого инженера нельзя назначить на смену',
    adminBlockedDatesEmpty: 'Нет заблокированных дат',
    adminBlockedDatesAdd: 'Заблокировать даты',
    adminBlockedDatesReason: 'Причина (необязательно)',
    save: 'Сохранить',
    delete: 'Удалить',
    reject: 'Отклонить',
    approve: 'Одобрить',
    open: 'Открыть',

    // Reminders
    reminders_title: 'Напоминания',
    active: 'Активные',
    all: 'Все',
    newReminder: '+ Создать',
    noReminders: 'Нет напоминаний',
    noRemindersDesc: 'Создайте первое напоминание',
    cancelReminder: 'Отменить',
    newReminderTitle: 'Новое напоминание',
    title: 'Заголовок',
    description: 'Описание',
    quickSet: 'Быстрый выбор',
    remindAt: 'Напомнить в',
    recurring: 'Повторять',
    telegram: 'Telegram',
    create: 'Создать',
    tomorrow: 'Завтра',

    // OTP
    twoFactor: 'Двухфакторная аутентификация',
    twoFactorDesc: 'Защитите аккаунт с помощью приложения (Google Authenticator, Authy и др.).',
    otpActive: '2FA включена',
    otpInactive: '2FA отключена',
    setupOtp: 'Настроить 2FA',
    otpScanQr: 'Отсканируйте QR-код в приложении-аутентификаторе, затем введите 6-значный код для подтверждения.',
    otpManualKey: 'Ручной ключ',
    otpEnterCode: '6-значный код',
    otpConfirm: 'Подтвердить и включить',
    otpEnabled: '2FA успешно включена',
    otpDisable: 'Отключить 2FA',
    otpDisableDesc: 'Введите код из приложения для отключения 2FA.',
    otpDisabled: '2FA отключена',

    // Time Off Page
    timeOffRequests: 'Выходные',
    timeOffDesc: 'Отпуска, больничные и выходные дни',
    noRequestsDesc: 'Заявок нет',
    timeOffRequested: 'Заявка отправлена!',

    // Telegram
    unlinkTelegram: 'Отвязать',
    telegramUnlinked: 'Telegram отвязан',

    // Mail Reporter
    mailReporter: 'Почта',
    mailboxes: 'Ящики',
    addMailbox: '+ Добавить ящик',
    editMailbox: 'Изменить ящик',
    deleteMailbox: 'Удалить ящик',
    testConnection: 'Проверить',
    pollNow: 'Проверить сейчас',
    recentEmails: 'Последние письма',
    noMailboxes: 'Нет настроенных ящиков',
    noMailboxesDesc: 'Добавьте ящик для мониторинга писем',
    noEmailLogs: 'Писем ещё не получено',
    emailAddress: 'Email адрес',
    appPassword: 'Пароль приложения',
    subjectFilter: 'Фильтр темы (ключевое слово или NONE)',
    telegramTarget: 'Telegram цель (chat_id или chat_id:thread_id)',
    monitorSince: 'Мониторить с',
    enabled: 'Включён',
    lastPoll: 'Последняя проверка',
    failures: 'Ошибок',
    never: 'Никогда',
    categoryAdobe: 'adobe',
    categoryOnboarding: 'онбординг',
    categoryOffboarding: 'оффбординг',
    categoryYandex: 'яндекс',
    categoryGeneral: 'общее',
    categoryFiltered: 'отфильтровано',
    clearLogs: 'Очистить',
    from: 'От',
    sent: 'Отправлено',
    failed: 'Ошибка',
    code: 'Код',

    // Common
    failedToLoad: 'Не удалось загрузить профиль. Обновите страницу.',
    loading: 'Загрузка…',
    select: 'Выбрать…',
    inOffice: 'В офисе',
    remote: 'Удалённо',
    draft: 'черновик',

    // Runbooks page
    rbCategoryAccess: 'Доступ',
    rbCategoryInfra: 'Инфра',
    rbCategoryYandex: 'Яндекс',
    rbCategoryWebsite: 'Сайт/CMS',
    rbCategoryOffice: 'Офис',
    rbCopy: 'Копировать',
    rbCopied: 'Скопировано',
    rbRun: 'Запустить',
    rbLogged: 'Выполнено',
    rbOwnedBy: 'Владелец:',
    rbUpdated: 'Обновлено',
    rbRunSingle: 'запуск',
    rbRunPlural: 'запусков',
    rbWhenToUse: 'Когда использовать',
    rbProcedure: 'Процедура',
    rbNoContent: 'Нет содержимого',
    rbNoContentDesc: 'Отредактируйте ранбук, чтобы добавить шаги.',
    rbStepsLabel: 'Шаги',
    rbStepTitlePlaceholder: 'Заголовок шага',
    rbStepDescPlaceholder: 'Описание (необязательно)',
    rbStepCodePlaceholder: 'Код (необязательно)',
    rbAddStep: 'Добавить шаг',
    rbEditTitle: 'Редактировать ранбук',
    rbNewTitle: 'Новый ранбук',
    rbCategoryLabel: 'Категория',
    rbOwnerLabel: 'Владелец',
    rbNoOwner: '— без владельца —',
    rbWhenToUsePlaceholder: 'Опишите, когда использовать этот ранбук…',
    rbTagsLabel: 'Теги (через запятую)',
    rbTitleRequired: 'Заголовок обязателен',
    rbSaving: 'Сохранение…',
    rbSaveChanges: 'Сохранить изменения',
    rbCreateRunbook: 'Создать ранбук',
    rbCreatedToast: 'Ранбук создан',
    rbSavedToast: 'Ранбук сохранён',
    rbDeleteConfirm: 'Удалить этот ранбук?',
    rbDeletedToast: 'Удалено',
    rbAllRunbooks: 'Все ранбуки',
    rbSearchPlaceholder: 'Поиск…',
    rbBrowse: 'Просмотр',
    rbNotFound: 'Ранбуки не найдены',
    rbStepSingular: 'шаг',
    rbStepPlural: 'шагов',
    rbSelectTitle: 'Выберите ранбук',
    rbSelectDesc: 'Выберите ранбук из списка, чтобы увидеть шаги.',

    // Command palette
    cmdPlaceholder: 'Перейти на страницу или найти ранбук…',
    cmdNoResults: 'Нет результатов для',
    cmdPages: 'Страницы',
    cmdRunbooksSection: 'Ранбуки',
    cmdNavigate: 'навигация',
    cmdOpen: 'открыть',
    cmdClose: 'закрыть',
    cmdResultSingular: 'результат',
    cmdResultPlural: 'результатов',
    cmdHintHome: 'Дашборд и обзор',
    cmdHintSchedule: 'Смены и расписание',
    cmdHintMail: 'Мониторинг почты',
    cmdHintTickets: 'Тикеты Zammad',
    cmdHintRunbooks: 'Плейбуки и процедуры',
    cmdHintTimeoff: 'Заявки на отгул',
    cmdHintReminders: 'Напоминания',
    cmdHintProfile: 'Профиль, 2FA, Telegram',
    cmdHintAdmin: 'Пользователи, настройки, журнал',
  },
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  useEffect(() => { localStorage.setItem('lang', lang); }, [lang]);

  const toggle = () => setLang(l => l === 'en' ? 'ru' : 'en');
  const t = key => translations[lang]?.[key] ?? translations.en[key] ?? key;

  return (
    <LangContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() { return useContext(LangContext); }
