"""add email body column

Revision ID: 7f3a8b9c1d2e
Revises: 6e35798b5fc6
Create Date: 2026-05-08 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3a8b9c1d2e'
down_revision = '6e35798b5fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_logs', op.f('body'), table_name='email_logs')
    # ### end Alembic commands ###
