"""initial_schema

Revision ID: 6e35798b5fc6
Revises: 
Create Date: 2026-04-07 14:47:23.161487+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e35798b5fc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mailbox_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('subject_filter', sa.String(length=200), nullable=False),
    sa.Column('telegram_target', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('monitor_since', sa.Date(), nullable=True),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailbox_configs_email'), 'mailbox_configs', ['email'], unique=True)
    op.create_table('shift_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shift_type', sa.Enum('day', 'night', 'office', name='shifttype'), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('default_start_time', sa.Time(), nullable=True),
    sa.Column('default_end_time', sa.Time(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('emoji', sa.String(length=4), nullable=True),
    sa.Column('requires_location', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_type')
    )
    op.create_table('shift_notification_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.Enum('day', 'night', 'office', name='shifttype'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'shift_type')
    )
    op.create_table('telegram_chats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('chat_type', sa.Enum('personal', 'group', 'channel', name='telegramchattype'), nullable=False),
    sa.Column('topic_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notify_day_shift_start', sa.Boolean(), nullable=True),
    sa.Column('notify_night_shift_start', sa.Boolean(), nullable=True),
    sa.Column('notify_office_roster', sa.Boolean(), nullable=True),
    sa.Column('notify_reminders', sa.Boolean(), nullable=True),
    sa.Column('notify_general', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('telegram_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'engineer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('name_color', sa.String(length=7), nullable=True),
    sa.Column('otp_secret', sa.String(length=32), nullable=True),
    sa.Column('otp_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('telegram_link_code', sa.String(length=20), nullable=True),
    sa.Column('telegram_notify_shifts', sa.Boolean(), nullable=True),
    sa.Column('telegram_notify_reminders', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('min_shift_gap_days', sa.Integer(), nullable=True),
    sa.Column('max_shifts_per_week', sa.Integer(), nullable=True),
    sa.Column('availability_pattern', sa.Text(), nullable=True),
    sa.Column('availability_anchor_date', sa.Date(), nullable=True),
    sa.Column('allowed_shift_types', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_table('mail_routing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('builtin_key', sa.String(length=50), nullable=True),
    sa.Column('match_type', sa.String(length=20), nullable=True),
    sa.Column('match_values', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('hashtag', sa.String(length=200), nullable=True),
    sa.Column('mention_users', sa.String(length=200), nullable=True),
    sa.Column('include_body', sa.Boolean(), nullable=True),
    sa.Column('telegram_target', sa.String(length=200), nullable=True),
    sa.Column('mailbox_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailbox_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('builtin_key')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'fired', 'cancelled', name='reminderstatus'), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_minutes', sa.Integer(), nullable=True),
    sa.Column('notify_telegram', sa.Boolean(), nullable=True),
    sa.Column('notify_in_app', sa.Boolean(), nullable=True),
    sa.Column('telegram_target', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_remind_at', 'reminders', ['remind_at'], unique=False)
    op.create_index('ix_reminders_user_id', 'reminders', ['user_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.Enum('day', 'night', 'office', name='shifttype'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.Enum('onsite', 'remote', name='worklocation'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'shift_type', name='uq_user_date_type')
    )
    op.create_index('ix_shifts_date', 'shifts', ['date'], unique=False)
    op.create_index('ix_shifts_user_id', 'shifts', ['user_id'], unique=False)
    op.create_table('time_off_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('off_type', sa.Enum('day_off', 'vacation', 'sick_leave', name='timeofftype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='timeoffstatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_groups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('vps_agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_template_id', sa.Uuid(), nullable=True),
    sa.Column('system_snapshot', sa.Text(), nullable=True),
    sa.Column('disk_alert_threshold', sa.Integer(), nullable=True),
    sa.Column('cpu_alert_threshold', sa.Integer(), nullable=True),
    sa.Column('alert_flags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['alert_template_id'], ['telegram_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('container_commands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('docker_id', sa.String(length=64), nullable=False),
    sa.Column('container_name', sa.String(length=255), nullable=True),
    sa.Column('command', sa.Enum('start', 'stop', 'restart', name='containercommandtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'executing', 'done', 'failed', name='containercommandstatus'), nullable=False),
    sa.Column('issued_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['vps_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('docker_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('state_detail', sa.Text(), nullable=True),
    sa.Column('ports', sa.Text(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('mem_usage_bytes', sa.Integer(), nullable=True),
    sa.Column('mem_limit_bytes', sa.Integer(), nullable=True),
    sa.Column('last_logs', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_absent', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hosted_on', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['vps_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'docker_id', name='uq_agent_docker')
    )
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mailbox_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=24), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('sender', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('telegram_sent', sa.Boolean(), nullable=False),
    sa.Column('telegram_target_used', sa.String(length=200), nullable=True),
    sa.Column('extracted_code', sa.String(length=20), nullable=True),
    sa.Column('skip_reason', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('solver_comment', sa.Text(), nullable=True),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailbox_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['mail_routing_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_logs_created_at', 'email_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_logs_fingerprint'), 'email_logs', ['fingerprint'], unique=True)
    op.create_index('ix_email_logs_mailbox_id', 'email_logs', ['mailbox_id'], unique=False)
    op.create_index('ix_email_logs_status', 'email_logs', ['status'], unique=False)
    op.create_table('email_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_comments')
    op.drop_index('ix_email_logs_status', table_name='email_logs')
    op.drop_index('ix_email_logs_mailbox_id', table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_fingerprint'), table_name='email_logs')
    op.drop_index('ix_email_logs_created_at', table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_table('container_commands')
    op.drop_table('container_states')
    op.drop_table('vps_agents')
    op.drop_table('user_groups')
    op.drop_table('time_off_requests')
    op.drop_index('ix_shifts_user_id', table_name='shifts')
    op.drop_index('ix_shifts_date', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index('ix_reminders_user_id', table_name='reminders')
    op.drop_index('ix_reminders_remind_at', table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('notifications')
    op.drop_table('mail_routing_rules')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_table('telegram_templates')
    op.drop_table('telegram_chats')
    op.drop_table('shift_notification_logs')
    op.drop_table('shift_configs')
    op.drop_index(op.f('ix_mailbox_configs_email'), table_name='mailbox_configs')
    op.drop_table('mailbox_configs')
    op.drop_table('groups')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # Drop PostgreSQL enum types (PostgreSQL only — SQLite has no native enum types)
    if op.get_context().dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS shifttype")
        op.execute("DROP TYPE IF EXISTS userrole")
        op.execute("DROP TYPE IF EXISTS telegramchattype")
        op.execute("DROP TYPE IF EXISTS reminderstatus")
        op.execute("DROP TYPE IF EXISTS worklocation")
        op.execute("DROP TYPE IF EXISTS timeofftype")
        op.execute("DROP TYPE IF EXISTS timeoffstatus")
        op.execute("DROP TYPE IF EXISTS containercommandtype")
        op.execute("DROP TYPE IF EXISTS containercommandstatus")
    # ### end Alembic commands ###
